### PR TITLE
FDS Source: Don't double count CHEM time in FIRE time

### PR DESCRIPTION
**Pull request by drjfloyd**

### CODE REVIEW

**Comment by mcgratta** [comment]
Aren't we losing track of the CPU time devoted to CHEM if we zero out T_USED(16)?

**Comment by drjfloyd** [comment]
Yikes. Yes. Thanks. It won't be quite that simple.

**Comment by mcgratta** [comment]
I would just turn off the FIRE clock just before calling CHEM and turn it back on when your return.

**Comment by drjfloyd** [comment]
CHEM is called in a select case that picks the integrator in a global loop inside of fire.  To save some CPU cycles and not have to muck with the fire clock in every grid cell, I will add a DTCHEM variable that is global in the fire module. Then in COMBUSTION we zero that out, around the call to CVODE we sum DTCHEM, and at the end of COMBUSTION we up T_USED(16) by DTCHEM and remove DTCHEM from T_USED(10).

**Comment by mcgratta** [comment]
If it gets too complicated, could we just retain FIRE only and assume that it is mostly CHEMistry?

**Comment by drjfloyd** [comment]
I'll make the PR after testing and let you look at it instead of just pushing it through. I think it is pretty simple. CHEM would dominate FIRE when using CVODE for more than a handful of reactions. We had added the CHEM timer in part so we could compare integration time with Cantera. Now that things seem to be working that may be less important.

**Pull request merged**
