### PR TITLE
FDS Source: Add GET_AVERAGE_SENSIBLE_SPECIFIC_HEAT, use in flame spee…

### PR DESCRIPTION
**Pull request by drjfloyd**
…d calc

### CODE REVIEW

**Comment by rmcdermo** [comment]
Jason,

Not a big deal, but you will notice in the diff of the files in your pull request that your editor is adding back a lot of the white spaces that I scrubbed out of the source code.  Can you see if you editor has a way to automatically clean this, or at least show them to you so that you can try not to add them.  I added this to the Developer Commit Guidelines because this tends to make the pull requests very noisy if all the white space stuff is random.

Also, please hold off on any more commits until we get Kevin's big pull merged.  There are a lot of conflicts he needs to sort out and we still need to figure out what is wrong with one of the verification cases.

Thanks.

**Comment by drjfloyd** [comment]
What are you and/or Kevin using for source edits on Windows? I've been using Visual Studio which I guess is deciding to add random spaces.

**Comment by mcgratta** [comment]
I haven't been using my Windows machine for code development. I use vi on our linux machine to edit code. Take a look at the diff's in your latest pull request. Do you think that the spaces are being added randomly, or could it be that these are lines that you've worked around. I see a few extra spaces at the end of a few lines, but more often I see differences in the blank lines. This might be a carriage return thing.

**Comment by drjfloyd** [comment]
All in did in func was add lines for the new function, yet I see random spaces inserted throughout the routine.  I guess it could be a carriage return thing?

**Comment by rmcdermo** [comment]
Jason,

Sublime Text 3 is available for Windows.

http://www.sublimetext.com/3

What Sublime does for me is at least show me that spaces are present with
very faint gray dots that are not annoying. (You can turn this off or on as
you want).

I wonder if Visual Studio has a similar option, just to show you when
you've added space?

I use Atom (GitHub editor) to do the cleaning of spaces from the files in
bulk.  It has an option to automatically clean white space upon saving the
file.

https://atom.io/

Atom is very similar to Sublime.  I think they based most of it on
Sublime.  But they do not give much control yet over having different
background themes for different file types, which I use frequently (for
example, I use dark background for FDS input files and light for source
code).

R

**Pull request merged**
