### PR TITLE
add IBLANK_SMV to &MISC line to control how smokeview handles iblank array creation

### PR DESCRIPTION
**Pull request by gforney**
smokeview at startup creates data structures for determining whether any given grid cell is within a blockage or not.  Among other things, this is used when displaying slice, 3d smoke and plot3d files for hiding data display within blockages (when viewed in outline mode).  The problem then is that for very large cases this data structure generation results in slow smokeview startup times.  

This pull request adds a more convenient way to stop blanking array initialization in smokeview by adding the IBLANK_SMV keyword to the the &MISC ( default value is .TRUE.)  To turn off blanking array generation in smokeview one would then set IBLANK_SMV=.FALSE. on the &MISC line .

### CODE REVIEW

**Comment by rmcdermo** [comment]
Glenn,
Please add this to FDS User Guide.  Thanks.

**Comment by rmcdermo** [comment]
Glenn,
I am going to set IBLANK_SMV=F by default.

**Comment by gforney** [comment]
this is going to break stuff.  Since we are releasing a bundle soon, I
would rather change it back to T until I figure out work arounds.

On Tue, Feb 9, 2016 at 11:52 AM, Randy McDermott notifications@github.com
wrote:

> Glenn,
> I am going to set IBLANK_SMV=F by default.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/firemodels/fds-smv/pull/3450#issuecomment-181953634.

## 

Glenn Forney

**Comment by rmcdermo** [comment]
OK.  I'll revert.

**Comment by gforney** [comment]
thanks

On Tue, Feb 9, 2016 at 1:56 PM, Randy McDermott notifications@github.com
wrote:

> OK. I'll revert.
> 
> On Tue, Feb 9, 2016 at 1:31 PM, Glenn Forney notifications@github.com
> wrote:
> 
> > this is going to break stuff. Since we are releasing a bundle soon, I
> > would rather change it back to T until I figure out work arounds.
> > 
> > On Tue, Feb 9, 2016 at 11:52 AM, Randy McDermott <
> > notifications@github.com
> > 
> > > wrote:
> > > 
> > > Glenn,
> > > I am going to set IBLANK_SMV=F by default.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/firemodels/fds-smv/pull/3450#issuecomment-181953634
> > > .
> > 
> > ## 
> > 
> > Glenn Forney
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/firemodels/fds-smv/pull/3450#issuecomment-181994337
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/firemodels/fds-smv/pull/3450#issuecomment-182003581.

## 

Glenn Forney

**Pull request merged**
