### PR TITLE
FDS source: correct short label for HRRPUV REAC slice file keyword - …

### PR DESCRIPTION
**Pull request by gforney**
…addresses issue 4000

### CODE REVIEW

**Comment by gforney** [comment]
randy,
accept this pull request if you haven't already made the same fix yourself and you agree that this will fix the problem for issue 4000
glenn

**Comment by gforney** [comment]
ps: was practicing with topic branches !

**Comment by rmcdermo** [comment]
Glenn,
Actually, this is an FDS/user problem.  I needed a REAC_ID on the SLCF line.  Then the short labels are different and everything works.  What I need to add is a trap for REAC_ID not being specified.  Sorry for the hassle!

**Comment by gforney** [comment]
No problem

**Comment by mcgratta** [comment]
Is this pull request still open?

**Comment by rmcdermo** [comment]
No.  I closed it 3 days ago.

**Pull request closed without merging**
