### PR TITLE
FDS Source: Remove AIR from BOUNDARY_FUEL_MODEL

### PR DESCRIPTION
**Pull request by mcgratta**

### CODE REVIEW

**Comment by ericvmueller** [comment]
Checking [ground_vegetation_load.fds](https://github.com/firemodels/fds/blob/master/Verification/WUI/ground_vegetation_load.fds), the in-depth density profile is now based on MATL density rather than MASS_PER_VOLUME on SURF:
image

Which causes issues elsewhere (the boundary fuel no longer burns in that case)

**Comment by mcgratta** [comment]
OK, let me see what's up.

**Comment by mcgratta** [comment]
I think we need to invoke `DENSITY_ADJUST_FACTOR`

**Comment by ericvmueller** [comment]
I had tried to use the calculated `PACKING_RATIO` to adjust the density but I think my issue was I had applied it directly to `LAYER_DENSITY` rather than `DENSITY_ADJUST_FACTOR`

**Comment by mcgratta** [comment]
I propose adding the last line of this chunk of code:
```
         ! Define BOUNDARY_FUEL_MODEL

         IF (SF%PACKING_RATIO(NL)>TWO_EPSILON_EB) THEN
            SF%BOUNDARY_FUEL_MODEL = .TRUE.
            SF%KAPPA_S(NL) = SHAPE_FACTOR*SF%PACKING_RATIO(NL)*SURFACE_VOLUME_RATIO(NL)
         ENDIF

         IF (MOISTURE_FRACTION(NL)>0._EB) THEN  ! Add MOISTURE
            MATL_ID(NL,NN) = 'MOISTURE'
            MATL_MASS_FRACTION(NL,NN) = MOISTURE_FRACTION(NL)/(1._EB+MOISTURE_FRACTION(NL))
            MATL_MASS_FRACTION(NL,1:NN-1) = MATL_MASS_FRACTION(NL,1:NN-1)*(1._EB-MATL_MASS_FRACTION(NL,NN))
         ENDIF

         IF (SF%BOUNDARY_FUEL_MODEL) SF%DENSITY_ADJUST_FACTOR(NL,:) = SF%DENSITY_ADJUST_FACTOR(NL,:)*SF%PACKING_RATIO(NL)
```

**Comment by ericvmueller** [comment]
I think it just needs to also check that PACKING_RATIO(NL)>0. Otherwise if you have something like a soil layer below it affects that too and causes issues.

**Comment by mcgratta** [comment]
This is implied by  `IF (SF%BOUNDARY_FUEL_MODEL)`

**Comment by ericvmueller** [comment]
But that is a whole surface property, not layer by layer

**Comment by mcgratta** [comment]
```
         IF (SF%BOUNDARY_FUEL_MODEL .AND. SF%PACKING_RATIO(NL)>TWO_EPSILON_EB) THEN
            SF%DENSITY_ADJUST_FACTOR(NL,:) = SF%DENSITY_ADJUST_FACTOR(NL,:)*SF%PACKING_RATIO(NL)
         ENDIF
```

**Comment by ericvmueller** [comment]
Let's give it a try and see how the verification cases go

**Pull request merged**
