### PR TITLE
Update FDS_User_Guide

### PR DESCRIPTION
**Pull request by sbenkorichi**
Update Solid Heat Transfer 3D (Beta)
Warning user from invoking MATL_ID on the SURF line.

### CODE REVIEW

**Comment by sbenkorichi** [comment]
@rmcdermo 
Randy, can you take a look at this once you are free.
I've added a warning for user to not specify the material on the surface line that is used in the OBST.

**Comment by rmcdermo** [comment]
Thanks Salah.  But actually, I'd rather just through an error if both HT3D and MATL_ID/='null'.  Can you submit this as an issue and assign me.  Thanks.

**Comment by rmcdermo** [comment]
Oh well... guess Kevin had a happy trigger finger.

**Comment by sbenkorichi** [comment]
LOL yes

**Comment by sbenkorichi** [comment]
I can submit an issue if you would like?

**Comment by rmcdermo** [comment]
Could not hurt to remind me to do it.

**Comment by sbenkorichi** [comment]
Ok, I've made an issue. However, I can't assign people for it. I guess I don't have the right for that.

**Pull request merged**
