### PR TITLE
FDS Source: add RAMP_CHI_R functionality

### PR DESCRIPTION
**Pull request by rmcdermo**

### CODE REVIEW

**Comment by rmcdermo** [comment]
Jason,
Will you do me a favor and run this new case and make the verification plot to double check that firebot will be happy with this?  Thanks.

**Comment by drjfloyd** [comment]
Will do.

**Comment by rmcdermo** [comment]
The plot is in dataplot under 'ramp_chi_r'.  Thanks.

**Comment by drjfloyd** [comment]
I get the attached (I haven't yet put time into getting the Git hash stuff
working on my system so my VerStr is empty).

**Comment by rmcdermo** [comment]
Jason,
I am not seeing your error.

**Comment by drjfloyd** [comment]
I had done a reply via email and just attached the plot pdf that resulted.  I guess that doesn't work via email. I get the plot below. To be clearer, it looks to be working to me as long as that is the plot formatting you were expecting.

[ramp_chi_r.pdf](https://github.com/firemodels/fds-smv/files/21975/ramp_chi_r.pdf)

**Comment by rmcdermo** [comment]
That looks fine. If you do not have the git hash the data plot routine
gives a dummy string. Thanks.

On Tuesday, October 27, 2015, Jason Floyd notifications@github.com wrote:

> I had done a reply via email and just attached the plot pdf that resulted.
> I guess that doesn't work via email. I get the plot below. To be clearer,
> it looks to be working to me as long as that is the plot formatting you
> were expecting.
> 
> ramp_chi_r.pdf
> https://github.com/firemodels/fds-smv/files/21975/ramp_chi_r.pdf
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/firemodels/fds-smv/pull/3004#issuecomment-151625173.

## 

Sent from my iPhone

**Pull request merged**
