### PR TITLE
FDS User Guide: Add COMB namelist group

### PR DESCRIPTION
**Pull request by mcgratta**

### CODE REVIEW

**Comment by drjfloyd** [comment]
Why a new namelist instead of just using REAC?

**Comment by mcgratta** [comment]
I moved the following parameters from `MISC` to `COMB`
```
{\ct CHECK\_REALIZABILITY}                      & Logical       & Section~\ref{info:chem_integration}                   &               & {\ct .FALSE.}        \\ \hline
%{\ct COMPUTE\_ZETA\_SOURCE\_TERM}               & Logical       & Section~\ref{}                                        &               & {\ct .FALSE.}        \\ \hline
{\ct EXTINCTION\_MODEL}                         & Character     & Section~\ref{info:extinction}                         &               & {\ct 'EXTINCTION 2'} \\ \hline
%{\ct HRRPUV\_MAX\_SMV}                          & Real          & Section~\ref{}                                        &  kW/m$^3$     & 1200                 \\ \hline
{\ct INITIAL\_UNMIXED\_FRACTION}                & Real          & Section~\ref{info:turbulent_combustion}               &               & 1.0                  \\ \hline
{\ct MAX\_CHEMISTRY\_SUBSTEPS}                  & Integer       & Section~\ref{info:chem_integration}                   &               & 20                   \\ \hline
{\ct N\_FIXED\_CHEMISTRY\_SUBSTEPS}             & Integer       & Section~\ref{info:chem_integration}                   &               & -1                   \\ \hline
{\ct RICHARDSON\_ERROR\_TOLERANCE}              & Real          & Section~\ref{info:chem_integration}                   &               & 1.0 E-6              \\ \hline
{\ct SUPPRESSION}                               & Logical       & Section~\ref{info:extinction}                         &               & {\ct .TRUE.}         \\ \hline
%{\ct TEMPERATURE\_DEPENDENT\_REACTION}          & Logical       & Compute mixed zone reactor temperature                &               & {\ct .FALSE.}        \\ \hline
%{\ct TRANSPORT\_UNMIXED\_FRACTION}              & Logical       & Section~\ref{}                                        &               & {\ct .FALSE.}        \\ \hline
%{\ct TRANSPORT\_ZETA\_SCHEME}                   & Integer       & Section~\ref{}                                        &               & 1                    \\ \hline
%{\ct WD\_PROPS}                                 & Logical       & Section~\ref{}                                        &               & {\ct .FALSE.}        \\ \hline
```
I left `SUPPRESSION` on the `MISC` line to maintain backward compatibility. It can be set on both `MISC` and `COMB`.

I want to have a place for global combustion parameters.

**Comment by mcgratta** [comment]
It is confusing now as to which REAC parameters are global, which get overwritten by a second REAC line, etc. Plus, MISC is getting to be too much of a catch-all. I found it difficult to find the various parameters that control combustion.

**Comment by drjfloyd** [comment]
Should we also move ODE_SOLVER, Y_P_MIN_EDC, TAU_CHEM, TAU_FLAME from REAC to COMB?

**Comment by mcgratta** [comment]
Yes, I'm working that now. I wanted to move the MISC parameters first, because they are global. I want to be careful with these others from the REAC line. For now, I'm just going to move parameters that most people would never use. In fact, the parameters you mention aren't in the U Guide, so it's safe to move them.

**Pull request merged**
