### PR TITLE
FDS Source: Allow MAX or MIN control function to work with a CONSTANT

### PR DESCRIPTION
**Pull request by mcgratta**

### CODE REVIEW

**Comment by mcgratta** [comment]
Jason -- FYI. Can you double check the ERROR messages for CONTROLs, They seem to be outdated.

**Comment by drjfloyd** [comment]
Yep, these have gotten stale. I'll reorganize the list in PREC to group the functions based on restrictions (i.e. something like type <100 are logical type 100 to 200 take one input, etc) and update read.

**Comment by drjfloyd** [comment]
Updated the error checking.

**Comment by mcgratta** [comment]
Great, thanks.

**Pull request merged**
