### PR TITLE
Reduce fdsplotlib pdf size 

### PR DESCRIPTION
**Pull request by johodges**

### CODE REVIEW

**Comment by rmcdermo** [comment]
Cool.  I'll give it a try.  What size were you able to get to?

**Comment by johodges** [comment]
It's 4kb now on my machine compared to the 3kb in Matlab.

**Comment by johodges** [comment]
I found this setting in the "core fonts" section of the matplotlib documentation. https://matplotlib.org/stable/users/explain/text/fonts.html

**Comment by rmcdermo** [comment]
@johodges I reran all the cases this morning and the `1_step_2_step_compare_MLRPUA.pdf` plot is showing 3.2 KB, which is great.  I think we are in business.

**Pull request merged**
