### PR TITLE
FDS Source: revert change to BAROCLINIC_CORRECTION that broke 2nd-ord…

### PR DESCRIPTION
**Pull request by rmcdermo**
…er temporal convergence

### CODE REVIEW

**Comment by mcgratta** [comment]
This will break the tunnel cases. In such cases H and HS are very
different, and using the wrong one on the first pressure iteration causes
trouble.

>

**Comment by rmcdermo** [comment]
Which cases

**Comment by rmcdermo** [comment]
Point me to the case that breaks.

**Comment by mcgratta** [comment]
Cases with TUNNEL_PRECONDITIONER. Often the H and HS profiles will be
counter-acting, like an upward V vs a downward V. By changing H to HS or
vis versa on the first step, the rate of convergence gets thrown off.

>

**Comment by rmcdermo** [comment]
I dialed back the repo to last night's source (passed firebot) and the `Pressure_Solver/tunnel_demo.fds` case fails if I use a single MPI process.  I can start an issue if you want.

With latest source (my change included) the `tunnel_demo` and `dancing_eddies` cases seem to be running fine.  I'll check the validation now.

**Pull request merged**
