### PR TITLE
pull changes to .gitignore

### PR DESCRIPTION
**Pull request by gforney**

### CODE REVIEW

**Comment by rmcdermo** [comment]
I guess we still do not understand Git very well.  It is weird that you just committed Jason's code.

**Comment by gforney** [comment]
I've seen that several times. Don't know other people s coomits show up in
my pull

**Comment by drjfloyd** [comment]
I went with the experiment of not cloning. Maybe I really need to do that?

**Comment by rmcdermo** [comment]
You mean not "forking".  But I don't think that's the problem.  We still see things that make us scratch our heads every now and then.

**Comment by rmcdermo** [comment]
I wonder if this has to do with "pull" versus "merge".  Glenn, do you do a "fetch + merge" or do you do a "pull"?  The latter, I think, does a "rebase", in which case what you are merging becomes part of your commit history.

**Comment by gforney** [comment]
I thought a "fetch + merge" was identical to a pull

On Fri, Jul 24, 2015 at 9:06 AM, Randy McDermott notifications@github.com
wrote:

> I wonder if this has to do with "pull" versus "merge". Glenn, do you do a
> "fetch + merge" or do you do a "pull"? The latter, I think, does a
> "rebase", in which case what you are merging becomes part of your commit
> history.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/firemodels/fds-smv/pull/2535#issuecomment-124514088.

## 

Glenn Forney

**Comment by rmcdermo** [comment]
It may depend on if you are using SmartGit or not.  In looking at git help
pull, it looks like you have to add --rebase to do the rebase.  But I think
SmartGit does this by default.

**Comment by gforney** [comment]
I may have used smartgit a couple of times to make commits but most of the
time I use the command line.  I"ll stick with the command line and see if
this comes up again

On Fri, Jul 24, 2015 at 9:12 AM, Randy McDermott notifications@github.com
wrote:

> It may depend on if you are using SmartGit or not. In looking at git help
> pull, it looks like you have to add --rebase to do the rebase. But I think
> SmartGit does this by default.
> 
> On Fri, Jul 24, 2015 at 9:08 AM, gforney notifications@github.com wrote:
> 
> > I thought a "fetch + merge" was identical to a pull
> > 
> > On Fri, Jul 24, 2015 at 9:06 AM, Randy McDermott <
> > notifications@github.com
> > 
> > > wrote:
> > > 
> > > I wonder if this has to do with "pull" versus "merge". Glenn, do you
> > > do a
> > > "fetch + merge" or do you do a "pull"? The latter, I think, does a
> > > "rebase", in which case what you are merging becomes part of your
> > > commit
> > > history.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/firemodels/fds-smv/pull/2535#issuecomment-124514088
> > > .
> > 
> > ## 
> > 
> > Glenn Forney
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/firemodels/fds-smv/pull/2535#issuecomment-124514560
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/firemodels/fds-smv/pull/2535#issuecomment-124515603.

## 

Glenn Forney

**Pull request merged**
