### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by saschagottfried**
Copied content from [current wiki page](https://github.com/firemodels/fds/wiki/FDS-SMV-Group-Policies). Added link to FDS and Smokeview (FDS-SMV) Discussion Group.

### CODE REVIEW

**Comment by saschagottfried** [comment]
Please delete the code of conduct wiki page after accepting this pull request.

**Comment by saschagottfried** [comment]
Finally I want to point out that GitHub provides excellent[ templates for code for conduct page](https://github.com/firemodels/fds/community/code-of-conduct/new). Chances are you find something useful to add to existing code of conduct page.

**Comment by saschagottfried** [comment]
I think the [Guidelines for effective posts](https://github.com/firemodels/fds/wiki/Effective-Posting#guidelines-for-creating-effective-posts) should be either part of [Contribution guidelines](https://github.com/firemodels/fds/blob/master/CONTRIBUTING.md) or [Code of Conduct](https://github.com/firemodels/fds/wiki/FDS-SMV-Group-Policies).

The notes on [Use of Copyrighted Material](https://github.com/firemodels/fds/wiki/Effective-Posting#use-of-copyrighted-material) likely belong to [Code of conduct](https://github.com/firemodels/fds/wiki/FDS-SMV-Group-Policies).

**Comment by rmcdermo** [comment]
@saschagottfried Thanks.  I'll look at the other wikis as soon as I get time.  Some of the language may be been dictated by NIST legal.  So I may have to dig through some of the history here.

**Comment by saschagottfried** [comment]
Sounds good. Thanks for accepting my contribution.

**Pull request merged**
