### PR TITLE
add VSRVC for 2D-PYRO3D

### PR DESCRIPTION
**Pull request by MortezaHaghighi**
Add missing case selection for the 2D case of PYRO3D

Issue #8230

### CODE REVIEW

**Comment by marcosvanella** [comment]
Looks like you have some tabs in this change. _db is throwing a warning.

**Comment by MortezaHaghighi** [comment]
Should I revert the PR, or it's editable?

**Comment by rmcdermo** [comment]
I'll deal with it.  Please set your editor to not use table.

**Comment by rmcdermo** [comment]
Should be fixed #9197

**Pull request merged**
