### PR TITLE
Remove blank pages

### PR DESCRIPTION
**Pull request by sbenkorichi**

### CODE REVIEW

**Comment by sbenkorichi** [comment]
Oh snap, don't accept it plz. I forgot to remove the previous modification of the bundle webpage.

**Comment by sbenkorichi** [comment]
I've fixed it back as it was.
Randy, How can I remove an old commit?

**Comment by rmcdermo** [comment]
Salah,
The only way to remove an old commit is via reset, which is dangerous.  It is better to just use revert, or overwrite the old commit with a correction.  If you use reset, you lose everything after it; reset should only be used if you do something locally that you want to correct immediately and really understand what you are about to reset.

**Comment by sbenkorichi** [comment]
Thanks for the info Randy, I will keep it in mind.

**Pull request merged**
