### PR TITLE
FDS Source: Avoid endless loop in 1-D heat transfer routine

### PR DESCRIPTION
**Pull request by mcgratta**

### CODE REVIEW

**Comment by mcgratta** [comment]
Jason -- take a look at this. The validation cases called SP_Wood_Cribs all hung up in SOLID_HEAT_TRANSFER_1D in a search loop with no backdoor exit.

**Comment by drjfloyd** [comment]
I'll take a look at it

**Comment by mcgratta** [comment]
The cases are working now. I added a backdoor. But just see if my max number of iterations is OK

**Comment by drjfloyd** [comment]
That number should be fine.

**Comment by drjfloyd** [comment]
I modified the backdoor to average the prior and current temperature. This is what is done elsewhere (see 1498 in hvac.f90). I checked this case and it is bouncing around between 782.9932 and 782.9938.

**Pull request merged**
