### PR TITLE
Complex Geometry routines

### PR DESCRIPTION
**Pull request by marcosvanella**
Hi Randy, here it is. I added Some verification cases we can start adding to the guides in Verification/Complex_Geometry:
- **sphere_cc_compute.fds, cube_cc_compute.fds**: Cut-cell definition for sphere and rotated cube and different mesh arrangements. Tests for correctness of computational geometry engine.
- **sphere_helium_1mesh.fds, sphere_helium_3meshes.fds**: Parallel consistency test on helium transport around sphere using GLMAT_SOLVER for pressure. Tests cut-cell definition, scalars exchange across meshes, IBM forcing across meshes and pressure interpolation. I sample out Velocities and H to a devc file, which should match for the 10 steps being run. 
- **sphere_helium_conserve_3meshes.fds**: Tests that amount of scalars is conserved for a 3 time unit run. 
- **sphere_propane_demo**: This is a demo of fire around sphere and 6 meshes. Combustion in cut-cellls is included.

If you want to test the GLMAT_SOLVER for pressure in the duct_flow.fds case add the line:
`&PRES GLMAT_SOLVER=.TRUE. /`
in that input file.

Remember we should run this through firebot. I haven't added anything to firebot verification/validation runs, so this pull request should not affect it.

### CODE REVIEW

**Comment by rmcdermo** [comment]
Marcos,
Thanks.  I will test.

**Comment by rmcdermo** [comment]
Marcos,
I have not tried to track this down, but for some reason mpi_intel_linux_64ib_db compile fine, but the release version mpi_intel_linux_64ib gives the following error:

openmp -qopenmp-link static -liomp5 ../../Source/mass.f90
../../Source/mass.f90(215): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [COMPLEX_GEOMETRY]
USE COMPLEX_GEOMETRY, ONLY : SET_EXIMADVFLX_3D,SET_DOMAINADVFLX_3D
----^
../../Source/mass.f90(215): error #6580: Name in only-list does not exist.   [SET_EXIMADVFLX_3D]
USE COMPLEX_GEOMETRY, ONLY : SET_EXIMADVFLX_3D,SET_DOMAINADVFLX_3D
-----------------------------^
../../Source/mass.f90(215): error #6580: Name in only-list does not exist.   [SET_DOMAINADVFLX_3D]
USE COMPLEX_GEOMETRY, ONLY : SET_EXIMADVFLX_3D,SET_DOMAINADVFLX_3D
-----------------------------------------------^
compilation aborted for ../../Source/mass.f90 (code 1)
make: *** [mass.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by marcosvanella** [comment]
Yes, I think it might be that we need to add complex_geometry as a dependency of mass in the makefile. If it is being compiled in parallel, a processor might pick up mass before geom.f90 has been compiled.

**Comment by rmcdermo** [comment]
Still does not work.  Are you sure you can compile on burn?  I don't understand how we are getting different results.

**Comment by marcosvanella** [comment]
I'll take a look in burn, I have been testing in my iMac.

**Comment by rmcdermo** [comment]
OK, I ran this through verification suite and no errors.  Your in!

**Pull request merged**
