### PR TITLE
make repo directory structure compatible with sub-modules

### PR DESCRIPTION
**Pull request by gforney**
DON'T ACCEPT THIS PULL REQUEST - for testing only

If we decide to split the FDS-SMV repo into various parts such as repos for FDS, SMV, experimental data, etc, we first need make some adjustments to the present directory structure to make it more modular and more consistent and to make the split easier.  

This pull request makes the directory structure for FDS and Smokeview consistent.  It creates a directory at the top level named FDS and puts FDS_Source and FDS_Compilation under FDS (renaming them Source and Build respectively - the smokeview source directory is also renamed from source to Source to be consistent).  In addition this pull request changes any script, makefile etc that references these directories to use the new directory names ie make_fds.sh or make_fds.bat will work.

both firebot and smokebot passed in my fork.  I want to test firebot in the pull request branch.

If anyone tests this pull request you should 
cd to top level of repo and type:
git clean -dxf

otherwise old directory locations will remain after you checkout the pull request branch

randy since this is for your project add any more background/motivation that you think will be useful

### CODE REVIEW

**Comment by rmcdermo** [comment]
@drjfloyd (and other Windows users) Just a heads up that we are working on a repo reorganization that will split FDS and SMV.  In the mean time, there will be some house cleaning to make the structures of these directories as similar as possible.  So, this might affect any Visual Studio hard-wired paths you have set when this merge takes place.

**Comment by gforney** [comment]
can we merge this pull request into a different branch ie a new branch named new_dev or do I need to generate another pull request?

**Comment by rmcdermo** [comment]
From a repo where origin tracks firemodels as remote do

git push -u origin dev_new

This will push the branch dev_new to the origin repo.

**Comment by rmcdermo** [comment]
You might want to test on your own fork first. :)

**Comment by gforney** [comment]
I changed the name of my branch (actually added a new branch named dev_new identical to dev_reorg).  dev_new is in my local repo and in my forked repo on github.  I want to put this branch into the firemodels repo on github.  would I do the following?

git push -u firemodels dev_new

**Comment by rmcdermo** [comment]
Yep.

**Comment by gforney** [comment]
thanks.  I pushed it up, so you can play with it when you get a chance

On Sat, Jun 25, 2016 at 9:26 PM, Randy McDermott notifications@github.com
wrote:

> Yep.
> 
> On Sat, Jun 25, 2016 at 8:39 PM, Glenn Forney notifications@github.com
> wrote:
> 
> > I changed the name of my branch (actually added a new branch named
> > dev_new
> > identical to dev_reorg). dev_new is in my local repo and in my forked
> > repo
> > on github. I want to put this branch into the firemodels repo on github.
> > would I do the following?
> > 
> > git push -u firemodels dev_new
> > 
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/firemodels/fds-smv/pull/4038#issuecomment-228577770
> > ,
> > or mute the thread
> > <
> > https://github.com/notifications/unsubscribe/AENrwfd4F0CAzNfF1_0oWrkbmgdjWn-hks5qPcpBgaJpZM4I-Be_
> > 
> > .
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/firemodels/fds-smv/pull/4038#issuecomment-228579056,
> or mute the thread
> https://github.com/notifications/unsubscribe/AL1BRppQN9yMq2aRUJsUSGLW8zLljkYqks5qPdUxgaJpZM4I-Be_
> .

## 

Glenn Forney

**Pull request closed without merging**
