### PR TITLE
FDS Source: cleanup CPU Time and Sim Time

### PR DESCRIPTION
**Pull request by rmcdermo**

### CODE REVIEW

**Comment by sbenkorichi** [comment]
Randy, 
What was the intention from changing the Simulation Time type. For 0.3s it turned to .3s and for 60s it turned to 1min. Is there a reason for this switch?

**Comment by rmcdermo** [comment]
That is not should be happening.  Show me an example with latest code.

**Comment by sbenkorichi** [comment]
I've just noticed it while running the cases.
```
fds-mpi ht3d_sphere_75.fds 
 Mesh 1 is assigned to MPI Process 0
 OpenMP thread   0 of   3 assigned to MPI process      0 of      0
 OpenMP thread   2 of   3 assigned to MPI process      0 of      0
 OpenMP thread   3 of   3 assigned to MPI process      0 of      0
 OpenMP thread   1 of   3 assigned to MPI process      0 of      0
 Completed Initialization Step  1
 Completed Initialization Step  2
 Completed Initialization Step  3
 Completed Initialization Step  4

 Fire Dynamics Simulator

 Current Date     : September 13, 2017  20:14:21
 Version          : FDS 6.5.3
 Revision         : FDS6.5.3-2557-gdf07a83-dirty
 Revision Date    : Wed Sep 13 15:32:13 2017 +0100
 Compiler         : Intel ifort 17.0.4
 Compilation Date : Sep 13, 2017  19:45:35

 MPI Enabled; Number of MPI Processes:          1
 OpenMP Enabled; Number of OpenMP Threads:   4

 MPI version: 3.1
 MPI library version: Open MPI v2.1.1, package: Open MPI salah@sbenkorichi Distribution, ident: 2.1.1, repo rev: v2.1.0-100-ga2fdb5b, May 10, 2017

 Job TITLE        : Heat transfer in solid sphere
 Job ID string    : ht3d_sphere_75

 Time Step: 1, Simulation Time: .1054E-01 s
 Time Step: 2, Simulation Time: .2108E-01 s
 Time Step: 3, Simulation Time: .3162E-01 s
 Time Step: 4, Simulation Time: .4216E-01 s
 Time Step: 5, Simulation Time: .5270E-01 s
 Time Step: 6, Simulation Time: .6325E-01 s
 Time Step: 7, Simulation Time: .7379E-01 s
 Time Step: 8, Simulation Time: .8433E-01 s
 Time Step: 9, Simulation Time: .9487E-01 s
 Time Step: 10, Simulation Time: .1054 s
 Time Step: 20, Simulation Time: .2108 s
 Time Step: 30, Simulation Time: .3162 s
 Time Step: 40, Simulation Time: .4216 s
 Time Step: 50, Simulation Time: .5270 s
 Time Step: 60, Simulation Time: .6325 s
 Time Step: 70, Simulation Time: .7379 s
 Time Step: 80, Simulation Time: .8433 s
 Time Step: 90, Simulation Time: .9487 s
 Time Step: 100, Simulation Time: 1.054 s
```
Then when it reaches 60s. it will turn to mins instead.

**Comment by rmcdermo** [comment]
No it won't.  Look at the source.  At 3600 s it will turn to h.

This commit gets rid of the "min"

**Comment by drjfloyd** [comment]
I would vote for keeping everything in seconds and making sure columns line up.  T_END is in seconds and if time in the screen dump changes to minutes, then I can't quickly see how far along the job is as I must first convert units.

**Comment by sbenkorichi** [comment]
Yeah, I would reckon it would turn to h after reaching it for sure. But, my question what was the purpose of changing it from seconds to this type of format?

**Comment by mcgratta** [comment]
No good deed goes unpunished. Glenn suggested I do this, but revert back to the way it was.

**Comment by rmcdermo** [comment]
This is small potatoes.  My code is a mess right now trying to fix real issues.  Move on.

**Comment by sbenkorichi** [comment]
Good Luck with that  ^ _ ^

**Pull request merged**
