### PR TITLE
FDS User Guide: add incomplete commented out table listing drag laws

### PR DESCRIPTION
**Pull request by btrettel**
Partially addresses issue #6258.

### CODE REVIEW

**Comment by rmcdermo** [comment]
Ben,
Documentation is in the FDS Tech Guide.

**Comment by btrettel** [comment]
Ah, thanks for pointing that out, no wonder I could not find the drag laws for spheres or cylinders in the users' guide.

**Comment by btrettel** [comment]
Fixed. Section numbers are hardcoded for now, and will need to be changed if the tech guide changes. I do not know how to automatically refer to sections in other TeX files.

The table is not commented out in this commit, and I have made a small change to the preceding paragraph to refer to the table.

**Comment by rmcdermo** [comment]
Don't hard code sections.  Either leave out the column or just say, "see FDS Tech Guide \cite{}"

**Pull request merged**
