### PR TITLE
Source: handle firebase presence in grid cell

### PR DESCRIPTION
**Pull request by usfs-fds**
Account for the subgrid fuel gas mass flux from level set modeled firebase (resolved or subgrid).

### CODE REVIEW

**Comment by drjfloyd** [comment]
Double check this. I think the change at line 2155 will break wall.f90.  No TAU_MF or RAMP_MF will be evaluated with this change unless a user sets BURN_DURATION but that would not be set for anything other than a WUI case.

**Comment by usfs-fds** [comment]
I think you are right. I'll fix this and resubmit.

**Comment by mcgratta** [comment]
This new code seems far more complicated than it needs to be. Could you write a short set of notes explaining what you are doing and I'll see if I can code it up more simply.

**Comment by mcgratta** [comment]
I will commit alternative code that does something similar.

**Pull request closed without merging**
