### PR TITLE
Embedded Lua Scripting

### PR DESCRIPTION
**Pull request by JakeOShannessy**
As part of my work I've always relied very heavily on the scripting capabilities of Smokeview to not only automate the production of results, but also to make them consistent and reproducible and to leave a specification for how those images etc. are obtained. However, I noticed myself pushing against the limits of what is available through the scripting interface and relied heavily on external software to produce series of combinations of .ini and .ssf files to produce the required results. I figured it would be much better to include this functionality in the post-processor itself.

This pull request adds the capability for Smokeview to be scripted via [Lua](http://www.lua.org/). This fulfils precisely the same purpose as the existing Smokeview scripting capabilities (SSF) but extends them and provides the capabilities of a full programming language (i.e. more than a series of actions). This language is purposefully designed to fulfil this kind of role, being very small and fast, and being built from only a small amount of standard (read portable) C.

By using a full programming language this allows us to defined variables, functions, and other control structures. For instance, if we wanted to loop through a list of times and render images:

``` lua
times = {0, 20 50, 75, 300, 400}
render.dir = "renders"
for k,v in pairs(times) do
  settime(v)
  render()
end
```

Or perhaps if we have two camera angles:

``` lua
cam1 = {projectionType = 0, eyePos = {x= 5...}...}
cam2 = {projectionType = 0, eyePos = {x= 10...}...}
times = {0, 20 50, 75, 300, 400}
for k,v in pairs(times) do
  settime(v)
  camera.set(cam1)
  render.dir = "renders/angle1"
  render()
  camera.set(cam2)
  render.dir = "renders/angle2"
  render()
end
```

As Lua is capable of importing other Lua files we can therefore specify functions that are shared across projects, as might be necessary if there are many scenarios for a single project. You might share cameras across models if the geometry is the same, or perhaps a certain setup for view certain variables. For instance:

``` lua
-- The following is a setup for view visibility in a standard form.
function visSetup()
  bounds.slices.set("VIS_C0.9H0.1", 0, 20)
  bounds.slices.set("VIS_Soot", 0, 20) -- to account for both names
  view.colorbar.index = 128
  view.colorbar.flip = true
end
```

As a lot of the functionality is described in Lua, it is also possible to modify it. For instance, we might have a particular format for describing out file inputs:

``` lua
cams = require "stdCameras" -- import the camera angles from a project wide file
projectName = "sampleproject"
camera.set(cams.overview)
visSetup()
render(function() return string.format("%s - %s - %d", projectName, model.chid,
    getframe()) end)
```

Which will assign the appropriate name for a rendered image depending on the value of those variables when the image is rendered.

Using the Lua interpreter also allows us to call out to external programs. For instance, the following code (which is included in a test case) utilises to external programs to create a movie from a model with two different data sets, and two different angles. The images are rendered, then stitched together, and then turned into a movie (this is used 'in production').

``` lua
function mkMovie()
    local cam = {
        rotationType = 1,
        eyePos = {x = 0.481481, y = -1.278639, z = 0.222222},
        ... -- additional specs
    }
    camera.set(cam)
    local movframes = 500
    load.datafile("room_fire_01.sf")
    render.dir = "renders/tempslice"
    rendermany(0,movframes,1,function() return tostring(view.framenumber) end)
    unload.all()
    render.dir ="renders/smoke"
    load.datafile("room_fire_01.s3d")
    rendermany(0,movframes,1,function() return tostring(view.framenumber) end)
    for i=0,movframes,1 do
        os.execute(string.format(
            "montage"
            .. " renders/tempslice/%d.png"
            .. " renders/smoke/%d.png"
            .. " -tile 2x1"
            .. " -geometry +0+0"
            .. " renders/combined/%d.png"
            , i, i, i))
    end
    os.execute(string.format(
        "ffmpeg"
        .. " -y"
        .. " -r 15"
        .. " -i renders/combined/%%d.png"
        .. " renders/testMovie.mp4"))
end
```

This PR adds two dependencies, Lua, which is essentially few number of C files, and lpeg, which is a parser written in Lua (this is used to parse SSF files so that the Lua interpreter can run SSF files directly). It also adds 2 new C files with their respective headers (c_api and lua_api) as well as directory of standard Lua files (smvluacore) to provide some out of the box functionality. All modifications to the existing C files are included under pp_LUA, and are only active when this is defined.

The C API is an abstraction of the functions in Smokeview. As the current scripting functionality is fairly heavily coupled with the parsing and running of script files it was necessary to either modify or duplicate these functions. It is intended that this C API form a fairly standard base from which the Lua interpreter can work from, in that way the interpreter has very little direct interaction with the Smokeview code and vice versa, forming a clean abstraction such that neither the interpreter or Smokeview should be sensitive to each other.

This PR has been added to both the mingw and gnu linux builds. I've been unable to test on other builds as I lack the compilers.

There is a test suite in Verification/Scripting. This can be run with $SMV -killscript -luascript test1.lua room_fire (where $SMV is the appropriate executable).

Obviously this is very much in the beta stage, but achieves the required functionality. Significant documentation is still required (only so much can be described in a pull request).

### CODE REVIEW

**Comment by gforney** [comment]
You've done a lot of work.  thanks for the contribution.  I'm taking a look at it.

**Comment by gforney** [comment]
Jake,
some preliminary comments.  first thanks for the bug fixes .  I've incorporated them in a separate fix.  I think I made them in the same way so they shouldn't interfere with what you have done.

Unfortunately I wasn't able to build a LUA enabled smokeview.  I got compiler errors (see below).  This could because I have a compiler that is out of date. (I was able to build smokeview in the development branch)

The structure of how LUA is incorpated into smokeview needs to change.  Basically LUA code should only be used when a lua script is run ie a .ssf script should not be run through the lua interpreter.  Also note, that in smokeview you can run scripts from the command line using 
smokeview -runscript casename
or you can run a script from the Load/Unload menu.  Therefore, smokeview won't necessarily know at the beginning what if any script is being run. (I noticed code where you read in a script at the beginning - not sure if you do something similar when a script is called form the menu)
1.  we need for the lua changes to be isolated as much as possible from the rest of smokeview at both compile and run time.  You've done a pretty good time of doing this at compile time with your pp_LUA directives.  The default value for LUA_SCRIPTING in the smokview Makefile should be false and then set to true in any scripts that builds a LUA enabled smokeview.

More importantly the LUA interpreter (or whatever you want to call it) should only be used when running lua scripts.  When running original smokeview scripts (.ssf files) the original smokeview method for running scripts should be used.
1.  smokeview doesn't build on our linux cluster using the gnu compiler

gcc -c -O0 -m64 -D pp_LINUX -D pp_LUA -I ../../source//include2/glut -I ../../source//include2/glui -I ../../source//include2/gd -I ../../source//shared -I ../../source//smokeview -I ../../source//glew -I ../../source//include2/zlib -I ../../source//lua-5.3.1/src ../../source//smokeview/main.c
In file included from ../../source//lua-5.3.1/src/lua.h:16,
                 from ../../source//smokeview/lua_api.h:1,
                 from ../../source//smokeview/main.c:13:
../../source//lua-5.3.1/src/luaconf.h:560:2: error: #error "Compiler does not support 'long long'. Use option '-DLUA_32BITS'   or '-DLUA_C89_NUMBERS' (see file 'luaconf.h' for details)"
In file included from ../../source//smokeview/lua_api.h:1,
                 from ../../source//smokeview/main.c:13:
../../source//lua-5.3.1/src/lua.h:93: error: expected '=', ',', ';', 'asm' or '**attribute**' before 'lua_Integer'
../../source//lua-5.3.1/src/lua.h:96: error: expected '=', ',', ';', 'asm' or '**attribute**' before 'lua_Unsigned'
../../source//lua-5.3.1/src/lua.h:182: error: 'lua_Integer' declared as function returning a function
../../source//lua-5.3.1/src/lua.h:182: warning: parameter names (without types) in function declaration
../../source//lua-5.3.1/src/lua.h:226: error: expected declaration specifiers or '...' before 'lua_Integer'
../../source//lua-5.3.1/src/lua.h:244: error: expected declaration specifiers or '...' before 'lua_Integer'
../../source//lua-5.3.1/src/lua.h:246: error: expected declaration specifiers or '...' before 'lua_Integer'
../../source//lua-5.3.1/src/lua.h:261: error: expected declaration specifiers or '...' before 'lua_Integer'
../../source//lua-5.3.1/src/lua.h:263: error: expected declaration specifiers or '...' before 'lua_Integer'
make: **\* [main.o] Error 1
1.  Here are errors for intel linux compiler

ifort -c -O0 -traceback -m64 -static-intel -fpp -D pp_noappend ../../../FDS_Source/gsmv.f90
../../source//smokeview/c_api.c(56): warning #2330: argument of type "const char *" is incompatible with parameter of type "char *" (dropping qualifiers)
    parse_smv_filepath(input_filename, fdsprefix, input_filename_ext);
                       ^

../../source//smokeview/c_api.c(413): warning #2330: argument of type "const char *" is incompatible with parameter of type "char *" (dropping qualifiers)
        RenderFrameLua(VIEW_CENTER, filename);
                                    ^

../../source//smokeview/c_api.c(481): warning #14: extra text after expected end of preprocessing directive
  #else defined(pp_LINUX)
        ^

../../source//smokeview/c_api.c(1011): error: identifier "X_SLICE" is undefined
        updateplotslice(X_SLICE);
                        ^

../../source//smokeview/c_api.c(1012): error: identifier "Y_SLICE" is undefined
        updateplotslice(Y_SLICE);
                        ^

../../source//smokeview/c_api.c(1013): error: identifier "Z_SLICE" is undefined
        updateplotslice(Z_SLICE);
                        ^

../../source//smokeview/c_api.c(1392): warning #2332: a value of type "const char *" cannot be assigned to an entity of type "char *" (dropping qualifiers)
                script_dir_path=dir;
                               ^

../../source//smokeview/lua_api.c(25): warning #267: the format string requires additional arguments
      printf("lua_loadsmvall filepath: %s\n");
                                            ^

../../source//smokeview/lua_api.c(134): error: identifier "runluascript" is undefined
      runluascript=1;
      ^

../../source//smokeview/lua_api.c(333): error: expected an expression
      for (int i; i < nglobal_times; i++) {
           ^

../../source//smokeview/lua_api.c(333): error: identifier "i" is undefined
      for (int i; i < nglobal_times; i++) {
                  ^

../../source//smokeview/lua_api.c(367): error: expected an expression
      for (int i; i < entries; i++) {
           ^

../../source//smokeview/lua_api.c(367): error: identifier "i" is undefined
      for (int i; i < entries; i++) {
                  ^

compilation aborted for ../../source//smokeview/c_api.c (code 2)
../../source//smokeview/lua_api.c(403): error: expected an expression
      for (int i; i < entries; i++) {
           ^

../../source//smokeview/lua_api.c(403): error: identifier "i" is undefined
      for (int i; i < entries; i++) {
                  ^

../../source//smokeview/lua_api.c(504): error: expected an expression
      for (int i; i < nsliceinfo; i++) {
           ^

../../source//smokeview/lua_api.c(504): error: identifier "i" is undefined
      for (int i; i < nsliceinfo; i++) {
                  ^

../../source//smokeview/lua_api.c(564): error: expected an expression
      for (int i; i < ncsvinfo; i++) {
           ^

../../source//smokeview/lua_api.c(564): error: identifier "i" is undefined
      for (int i; i < ncsvinfo; i++) {
                  ^

make: **\* [c_api.o] Error 2
make: **\* Waiting for unfinished jobs....
../../source//smokeview/lua_api.c(1218): error: identifier "luascript_filename" is undefined
      if (strlen(luascript_filename) == 0) {
                 ^

../../source//smokeview/lua_api.c(1227): error: identifier "runluascript" is undefined
      runluascript=0;
      ^

compilation aborted for ../../source//smokeview/lua_api.c (code 2)
make: **\* [lua_api.o] Error 2
[g
1.  noticed some minor problems with text line endings.  c_api.c has dos line endings.  Not sure how to do this in git but there is a way to store files so line endings are correct for both Windows and linux/osx repos

See if you can address my suggestions and try another pull request.
glenn

**Comment by JakeOShannessy** [comment]
Thanks for looking at this Glenn, I appreciate it.

I don't have those problems on either of my compiler setups, so I'll have to investigate reproducing them. On a side note, I can update this pull request (and thereby keep all the discussion in one place) if you'd prefer (it would need to be reopened), or I can of course make a new pull request, whatever workflow best suits.
1. Leaving the original SSF code path seems like the better choice, I've updated the code such that even with pp_LUA enabled it is only used for Lua scripts. My initial thoughts were that by doing this I would be forced to make sure that the Lua scripting is able to adequately reproduce anything the SSF scripts could do. For this reason I've left the SSF capability in the codebase to test the Lua functionality, but it's never actually called into action. I've redesigned the loading of scripts to mimic the SSF functionality a closely a is relevant for the Lua scripts, including the menus. Even if this doesn't fit the setup of the Lua scripting, at least it provides consistency for everybody who looks at the code.
2. I've accounted for all of the errors given by the Intel compiler (there were a few constants I failed to update after merging with the development branch). The gcc error is proving a little difficult to reproduce, I've tried a number of gcc versions and standards settings (C89, C90, etc.) but to no avail. I've modified Lua to use C89, which looks like it might be the issue given the error message, but I have no way to test this. Is there anymore information you can give me on the compiler setup you use, such as version number etc.? If it is a package from a standard linux distribution this might be easier to reproduce. It shouldn't be your responsibility to track down errors I've triggered for these builds.
3. Line endings have been corrected. My git is set to work as-is with UNIX (LF) style line endings, the new files were simply created as CRLF on my Windows machine. I've fixed these defaults. This has been all been updated in a single commit before any of the bug fixes (to make it easier to read changes). This commit does not include any other changes (except a slight mingw build fix).

I've made these changes and pushed them to my luaScripting branch (i.e. the branch in this pull request). I've re-tested both Lua and SSF scripting in this new setup and everything seems to function much the same (without numerically testing the output). I'll see what else I can do about emulating your build setup. Any information you have would be helpful.

**Comment by gforney** [comment]
I've reopened this pull request so that Jake can respond here to my comments

**Comment by gforney** [comment]
fyi:  here are more details on errors and gcc versions for the systems I tried
1.  Centos 5.5 linux system - lua built, smokeview had errors below
   gcc --version
   gcc (GCC) 4.1.2 20080704 (Red Hat 4.1.2-52)
   Copyright (C) 2006 Free Software Foundation, Inc.
   This is free software; see the source for copying conditions.  There is NO
   warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[gforney@blaze gnu_linux_64]$ ./make_smv.sh
gcc -c -O0 -m64 -D pp_LINUX -D pp_LUA -I ../../source//include2/glut -I ../../source//include2/glui -I ../../source//include2/gd -I ../../source//shared -I ../../source//smokeview -I ../../source//glew -I ../../source//include2/zlib -I ../../source//lua-5.3.1/src ../../source//smokeview/main.c
In file included from ../../source//lua-5.3.1/src/lua.h:16,
                 from ../../source//smokeview/lua_api.h:1,
                 from ../../source//smokeview/main.c:13:
../../source//lua-5.3.1/src/luaconf.h:560:2: error: #error "Compiler does not support 'long long'. Use option '-DLUA_32BITS'   or '-DLUA_C89_NUMBERS' (see file 'luaconf.h' for details)"
In file included from ../../source//smokeview/lua_api.h:1,
                 from ../../source//smokeview/main.c:13:
../../source//lua-5.3.1/src/lua.h:93: error: expected '=', ',', ';', 'asm' or '**attribute**' before 'lua_Integer'
../../source//lua-5.3.1/src/lua.h:96: error: expected '=', ',', ';', 'asm' or '**attribute**' before 'lua_Unsigned'
../../source//lua-5.3.1/src/lua.h:182: error: 'lua_Integer' declared as function returning a function
../../source//lua-5.3.1/src/lua.h:182: warning: parameter names (without types) in function declaration
../../source//lua-5.3.1/src/lua.h:226: error: expected declaration specifiers or '...' before 'lua_Integer'
../../source//lua-5.3.1/src/lua.h:244: error: expected declaration specifiers or '...' before 'lua_Integer'
../../source//lua-5.3.1/src/lua.h:246: error: expected declaration specifiers or '...' before 'lua_Integer'
../../source//lua-5.3.1/src/lua.h:261: error: expected declaration specifiers or '...' before 'lua_Integer'
../../source//lua-5.3.1/src/lua.h:263: error: expected declaration specifiers or '...' before 'lua_Integer'
make: **\* [main.o] Error 1
1.  Ubuntu 14.04 linux system - Lua built, smokeview build errors below
   
   gcc -v
   Using built-in specs.
   COLLECT_GCC=gcc
   COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
   Target: x86_64-linux-gnu
   Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.2-19ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
   Thread model: posix
   gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1)

../../source//smokeview/c_api.c:56:3: warning: passing argument 1 of âparse_smv_filepathâ discards âconstâ qualifier from pointer target type [enabled by default]
   parse_smv_filepath(input_filename, fdsprefix, input_filename_ext);
   ^
In file included from ../../source//smokeview/c_api.c:14:0:
../../source//smokeview/c_api.h:117:5: note: expected âchar _â but argument is of type âconst char *â
 int parse_smv_filepath(char *smv_filepath, char *fdsprefix,
     ^
../../source//smokeview/c_api.c: In function âparse_smv_filepathâ:
../../source//smokeview/c_api.c:94:9: warning: format â%dâ expects argument of type âintâ, but argument 2 has type âsize_tâ [-Wformat=]
         printf("fdsprefixlen1: %d\n", strlen(fdsprefix));
         ^
../../source//smokeview/c_api.c:96:9: warning: format â%dâ expects argument of type âintâ, but argument 2 has type âsize_tâ [-Wformat=]
         printf("fdsprefixlen2: %d\n", strlen(fdsprefix));
         ^
../../source//smokeview/c_api.c: In function ârenderâ:
../../source//smokeview/c_api.c:413:2: warning: passing argument 2 of âRenderFrameLuaâ discards âconstâ qualifier from pointer target type [enabled by default]
  RenderFrameLua(VIEW_CENTER, filename);
  ^
In file included from ../../source//smokeview/c_api.c:14:0:
../../source//smokeview/c_api.h:112:6: note: expected âchar *â but argument is of type âconst char *â
 void RenderFrameLua(int view_mode, char *basename);
      ^
../../source//smokeview/c_api.c: In function âform_filenameâ:
../../source//smokeview/c_api.c:481:7: warning: extra tokens at end of #else directive [enabled by default]
 #else defined(pp_LINUX)
       ^
../../source//smokeview/c_api.c: In function âplot3dpropsâ:
../../source//smokeview/c_api.c:1011:23: error: âX_SLICEâ undeclared (first use in this function)
       updateplotslice(X_SLICE);
                       ^
../../source//smokeview/c_api.c:1011:23: note: each undeclared identifier is reported only once for each function it appears in
../../source//smokeview/c_api.c:1012:23: error: âY_SLICEâ undeclared (first use in this function)
       updateplotslice(Y_SLICE);
                       ^
../../source//smokeview/c_api.c:1013:23: error: âZ_SLICEâ undeclared (first use in this function)
       updateplotslice(Z_SLICE);
                       ^
../../source//smokeview/c_api.c: In function âsetrenderdirâ:
../../source//smokeview/c_api.c:1392:18: warning: assignment discards âconstâ qualifier from pointer target type [enabled by default]
   script_dir_path=dir;
                  ^
make: *_\* [c_api.o] Error 1

My windows at system does not have mingw installed yet - I'll send you the errors I got on y home pc later this evening

**Comment by JakeOShannessy** [comment]
Thanks, Glenn. I might struggle to reproduce gcc 4.1.2, but I should be able to reproduce the Ubuntu gcc-4.8 setup. The errors given by the Ubuntu setup (X_SLICE, Y_SLICE, and Z_SLICE undefined) were fixed in the latest commits (the constants were redefined). Are you able to pull down this branch and try it again? I have a few virtual machines that can run gcc-4.8 fairly easily (one of which is Ubuntu) so I'll try and get that build/platform sorted first. Once I get those errors sorted then the other warnings should not be too much of an issue.

If you're looking at setting up mingw on your own machine remember to go for MSYS and mingw64, working out which thing you need to install can sometimes be a pain, but once you work it out it makes working in open source projects much easier.

**Comment by gforney** [comment]
I've been doing a lot of code cleanup - think I got rid of X_SLICE, Y_SLICE, Z_SLICE in favor of the already used XDIR, YDIR and ZDIR

Can one install gcc on a system without uninstalling the gcc that is already there.  It is difficult to make changes on our main cluster head node which is what has the older gcc

**Comment by JakeOShannessy** [comment]
Yes, I believe I made a last minute merge before my original pull request that I didn't adequately recompile for, and missed that change.

On some systems it is certainly easier than others to run multiple compilers. One of the Linux VMs I run uses the Nix package manager (with the NixOS distribution of Linux incidentally) which makes it absolutely trivial to have as many versions of any software as I want, and just specify what kind of setup I want each time I go to compile or even open a shell. Unfortunately gcc is only prepackaged for Nix back to version 4.4 (latest is 5.2), and I'm not sure I'd be able to personally package a 4.1 version myself.

I imagine installing different on your cluster would be quite big process with large ramifications, it makes much more sense for people like us to be able to reproduce your build setup. I tend to use fairly ephemeral setups such as Nix and VMs anyway, so it's not like I can break anything important on my end.

I did manage to find a repository for Ubuntu (and probably Debian for that matter) which has gcc-4.1 still. Most of the easier to find older releases only date back to 4.4. My plan from here is to build a VM from this. I may also look for a CentOS setup and try and mirror your cluster as much as possible. Fortunately once I have this set up I can document it so that anyone else who want to participate can also reproduce your build conditions freely and easily. Reproducing the Intel conditions is obviously a bit harder because of licensing, but if people can use a shared VM at least we have a common language for testing.

**Comment by JakeOShannessy** [comment]
I was able to setup a CentOS 5.5 VM with gcc (and gfortran) 4.1.2 20080704 (Red Hat 4.1.2-55) (not -52, but I've tested -48 with the same result) but this resulted in some Fortran errors in `gsmv.f90`:

```
  In file ../../../FDS_Source/gsmv.f90:1426

    TETRAVERT(0:2) => TETRA_VERTS(0:2,TETRA_PLANE2VERT(0,TP))
            1
```

So I'll have to keep looking. I'll keep you posted.

**Comment by gforney** [comment]
I dont' see how to update the test branch I created for your original pull
request to incorporate changes you have made since the pull request.

On Fri, Feb 5, 2016 at 4:38 PM, JakeOShannessy notifications@github.com
wrote:

> Yes, I believe I made a last minute merge before my original pull request
> that I didn't adequately recompile for, and missed that change.
> 
> On some systems it is certainly easier than others to run multiple
> compilers. One of the Linux VMs I run uses the Nix package manager (with
> the NixOS distribution of Linux incidentally) which makes it absolutely
> trivial to have as many versions of any software as I want, and just
> specify what kind of setup I want each time I go to compile or even open a
> shell. Unfortunately gcc is only prepackaged for Nix back to version 4.4
> (latest is 5.2), and I'm not sure I'd be able to personally package a 4.1
> version myself.
> 
> I imagine installing different on your cluster would be quite big process
> with large ramifications, it makes much more sense for people like us to be
> able to reproduce your build setup. I tend to use fairly ephemeral setups
> such as Nix and VMs anyway, so it's not like I can break anything important
> on my end.
> 
> I did manage to find a repository for Ubuntu (and probably Debian for that
> matter) which has gcc-4.1 still. Most of the easier to find older releases
> only date back to 4.4. My plan from here is to build a VM from this. I may
> also look for a CentOS setup and try and mirror your cluster as much as
> possible. Fortunately once I have this set up I can document it so that
> anyone else who want to participate can also reproduce your build
> conditions freely and easily. Reproducing the Intel conditions is obviously
> a bit harder because of licensing, but if people can use a shared VM at
> least we have a common language for testing.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/firemodels/fds-smv/pull/3439#issuecomment-180567394.

## 

Glenn Forney

**Comment by gforney** [comment]
I'm getting the same errors as you compiling gsmv.f90 (we are using features only supported in more recent Fortran compilers) in our development branch on our Centos 5.5 system (running gcc 4.1.2-52).  I've been building smokeview on a number of systems and got mixed up where the failures were occurring . I am able to build smokeview (in development branch) using gnu C/C++ 4.8.2 .  So forget Centos 5.5 - just look at platforms that can support this c/c++/gfortran.

Once I can update the pull request branch to your most recent changes, I'll try building the lua enabled smokeview again

**Comment by gforney** [comment]
jake,
do you still want to do this?

**Comment by JakeOShannessy** [comment]
Absolutely, I still use this branch for my own work actively. Were you able to build the latest commit from my branch?

**Comment by gforney** [comment]
I don't see how to get  your latest commit - the message above says that there are conflicts

**Comment by JakeOShannessy** [comment]
Ahhh, presumably the branch you are pulling into is one you have also made changes to (i.e. maybe you are using a branch that tracks development). The best way to avoid this is to use a separate local branch for this pull request. For now though, I will just merge in any changes from this repo's development branch. Obviously this will grow out of date, but it needs to be done anyway.

**Comment by JakeOShannessy** [comment]
I've merged the two branches now Glenn, so you should be able to pull onto your development branch if that's your workflow. I've tested both with and without Lua and it's working fine for me.

**Comment by gforney** [comment]
fyi: guess you see that I accepted your pull request .  thanks of isolating your lua code within pp_LUA directives

I found a couple of minor errrors.  
1. in c_api.c near line 481  my preprocessor/compiler didn't like this line 
   #else defined(pp_LINUX)  

I changed this section of code to
 #ifdef MINGW
                 mkdir(renderfile_dir);
#endif
+#ifdef pp_LINUX
- ```
             mkdir(renderfile_dir, 0755);
  ```
  
  +#endif
  +#ifdef pp_OSX
               mkdir(renderfile_dir, 0755);
  #endif
1.  in lua_api.c near line 73 , think you missed an argument to printf .  I guessed you meant to use filepath - as in

printf("lua_loadsmvall filepath: %s\n",filepath);
1.  I added script and modified makefile entries to build lua/intel smokeview for osx and intel .  haven't tried it yet though

**Comment by JakeOShannessy** [comment]
Thanks, Glenn. I fixed the pre-processor error this morning along with a few warnings. When I last compiled I had no warnings. I'll re-merge with the other two changes.

**Comment by gforney** [comment]
check the latest changes I just pulled into firemodels.

I can now build on linux and osx using the intel compilers (lua is built
using gcc which is fine). I'm working on getting lua smokeview to  using
intel win compilers.

On Mon, Feb 22, 2016 at 3:22 PM, JakeOShannessy notifications@github.com
wrote:

> Thanks, Glenn. I fixed the pre-processor error this morning along with a
> few warnings. When I last compiled I had no warnings. I'll re-merge with
> the other two changes.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/firemodels/fds-smv/pull/3439#issuecomment-187368130.

## 

Glenn Forney

**Pull request merged**
