### PR TITLE
Update Firebot Figure Script and Update User Guide to add chemistry subiterations

### PR DESCRIPTION
**Pull request by cweinschenk**

### CODE REVIEW

**Comment by rmcdermo** [comment]
Craig,
This is better, but you need to correct the Copy_Firebot_Figures.sh script.  Or, if this does not work for you we may need to not keep this under version control.  But I found I needed to make the changes I made in order to make it work with current Firebot.

**Comment by cweinschenk** [comment]
The version as it existed in the repository did not work which is why I made changes.

**Comment by rmcdermo** [comment]
Hmmm... works on my end.  We should get this sorted out.  It is a useful
script.  Are you on burn?  Not sure why it would be different.  Maybe Glenn
has an idea.

On Tue, Sep 22, 2015 at 10:05 AM, Craig Weinschenk <notifications@github.com

**Comment by cweinschenk** [comment]
I am on Blaze. That could be why. I converted the script back and submitted a new pull request with just the user guide changes.

**Comment by rmcdermo** [comment]
Glenn,
Does this behavior make sense to you?

If so, I suggest Craig commits his version as Copy_Firebot_Figures_Blaze.sh
and I'll do likewise for Burn.

On Tue, Sep 22, 2015 at 10:45 AM, Craig Weinschenk <notifications@github.com

**Comment by gforney** [comment]
what doesn't work?

**Comment by rmcdermo** [comment]
See the Copy_Firebot_Figures.sh changes from pull requiest 2807.

https://github.com/firemodels/fds-smv/pull/2807/files#diff-0

On blaze, Craig needs to make these changes.  On burn, the original works
fine for me.  Does it make sense that we might need two scripts?

**Comment by cweinschenk** [comment]
I logged out of blaze and burn and relogged in and now both scripts seems to be functioning now. I guess it was something to do with Smokevis or something

**Pull request closed without merging**
