### PR TITLE
FDS Source : Make SANDIA_OUT call happen when PERIODIC_TEST=9.

### PR DESCRIPTION
**Pull request by marcosvanella**

### CODE REVIEW

**Comment by mcgratta** [comment]
Sorry, forgot to uncomment CASE(9)

**Comment by marcosvanella** [comment]
Kevin no problem there seem to be errors in the restart functionality. Not sure if that is related to more clock changes commit too.
________________________________

**Comment by mcgratta** [comment]
Is there a case to look at?

**Comment by marcosvanella** [comment]
These two:

Restart/geom_restart_b.err:forrtl: severe (174): SIGSEGV, segmentation fault occurred
Restart/geom_restart_b.err-Image              PC                Routine            Line        Source
Restart/geom_restart_b.err-fds_impi_intel_li  00000000070C762A  Unknown               Unknown  Unknown
Restart/geom_restart_b.err-libpthread-2.17.s  00002B1002178630  Unknown               Unknown  Unknown
Restart/geom_restart_b.err-fds_impi_intel_li  000000000727CDD9  Unknown               Unknown  Unknown
Restart/geom_restart_b.err-fds_impi_intel_li  000000000725159E  Unknown               Unknown  Unknown
Restart/geom_restart_b.err-fds_impi_intel_li  000000000722E25F  Unknown               Unknown  Unknown
Restart/geom_restart_b.err-fds_impi_intel_li  00000000071A63F4  Unknown               Unknown  Unknown
Restart/geom_restart_b.err-fds_impi_intel_li  000000000040B522  Unknown               Unknown  Unknown
Restart/geom_restart_b.err-libc-2.17.so       00002B1004ABF555  __libc_start_main     Unknown  Unknown
Restart/geom_restart_b.err-fds_impi_intel_li  000000000040B429  Unknown               Unknown  Unknown
Restart/geom_restart_b.err-srun: error: blaze109: task 0: Exited with exit code 174
Restart/geom_restart_b.err-srun: Terminating job step 3308180.0
--
Restart/pyro3d_restart_b.err:forrtl: severe (67): input statement requires too much data, unit 34, file /home2/smokevis2/firebot/FireModels_clone/fds/Verification/Restart/pyro3d_restart_1.restart
Restart/pyro3d_restart_b.err-Image              PC                Routine            Line        Source
Restart/pyro3d_restart_b.err-fds_impi_intel_li  00000000070B8FB8  Unknown               Unknown  Unknown
Restart/pyro3d_restart_b.err-fds_impi_intel_li  00000000070E8B4B  Unknown               Unknown  Unknown
Restart/pyro3d_restart_b.err-fds_impi_intel_li  000000000795DD0E  Unknown               Unknown  Unknown
Restart/pyro3d_restart_b.err-fds_impi_intel_li  00000000071A8325  Unknown               Unknown  Unknown
Restart/pyro3d_restart_b.err-fds_impi_intel_li  000000000040B522  Unknown               Unknown  Unknown
Restart/pyro3d_restart_b.err-libc-2.17.so       00002B3C5DF2B555  __libc_start_main     Unknown  Unknown
Restart/pyro3d_restart_b.err-fds_impi_intel_li  000000000040B429  Unknown               Unknown  Unknown
Restart/pyro3d_restart_b.err-srun: error: blaze109: task 0: Exited with exit code 67
Restart/pyro3d_restart_b.err-srun: Terminating job step 3308179.0

I checked the first one, for that you run first geom_restart_a.fds and then geom_restart_b.fds (same with the pyro case).
For the geom one I tried dv and got this at the start of _b.fds:

 Fire Dynamics Simulator

 Current Date     : January 13, 2022  09:16:31
 Revision         : FDS6.7.7-476-gd1e1d205a-dirty-master
 Revision Date    : Thu Jan 13 08:53:15 2022 -0500
 Compiler         : Intel ifort 2021.4.0
 Compilation Date : Jan 13, 2022  08:55:36

 MPI Enabled;    Number of MPI Processes:       1
 OpenMP Enabled; Number of OpenMP Threads:      1

 MPI version: 3.1
 MPI library version: Open MPI v4.1.0, package: Open MPI ***@***.*** Distribution, ident: 4.1.0, repo rev: v4.1.0, Dec 18, 2020

 Job TITLE        : Test restart behaviour
 Job ID string    : geom_restart

forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
fds_mpi_intel_osx  0000000109BB8984  Unknown               Unknown  Unknown
libsystem_platfor  00007FFF708F65FD  Unknown               Unknown  Unknown
fds_mpi_intel_osx  0000000103A5CDC4  _velo_mp_velocity        1958  velo.f90
fds_mpi_intel_osx  0000000103C0309C  _MAIN__                   702  main.f90
fds_mpi_intel_osx  000000010374262E  Unknown               Unknown  Unknown
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------

Seems something is corrupted in the restart file, couldn't make much of the line where things go bad.
________________________________

**Comment by marcosvanella** [comment]
I'm running the cases in db mde now. The line in velo.f90 is related to a WALL_INDEX assignment.
________________________________

**Comment by marcosvanella** [comment]
This is what I'm getting in db mode:

 Starting FDS ...

 MPI Process      0 started on bevo.el.nist.gov

 Reading FDS input file ...


 Fire Dynamics Simulator

 Current Date     : January 13, 2022  09:45:45
 Revision         : FDS6.7.7-476-gd1e1d205a-dirty-master
 Revision Date    : Thu Jan 13 08:53:15 2022 -0500
 Compiler         : Intel ifort 2021.4.0
 Compilation Date : Jan 13, 2022  09:18:27

 MPI Enabled;    Number of MPI Processes:       1
 OpenMP Enabled; Number of OpenMP Threads:      1

 MPI version: 3.1
 MPI library version: Open MPI v4.1.0, package: Open MPI ***@***.*** Distribution, ident: 4.1.0, repo rev: v4.1.0, Dec 18, 2020

 Job TITLE        : Test restart behaviour
 Job ID string    : geom_restart

forrtl: error (73): floating divide by zero
Image              PC                Routine            Line        Source
fds_mpi_intel_osx  000000011902477A  Unknown               Unknown  Unknown
libsystem_platfor  00007FFF708F65FD  Unknown               Unknown  Unknown
fds_mpi_intel_osx  0000000112D205C9  _divg_mp_divergen          59  divg.f90
fds_mpi_intel_osx  0000000112E8FDCE  _MAIN__                   624  main.f90
fds_mpi_intel_osx  000000010E6A2A2E  Unknown               Unknown  Unknown
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------

Which tells us that the DT being read in from the restart file (or computed after restart?) is zero.
________________________________

**Pull request merged**
