### PR TITLE
FDS Source: Extend WALL functions to CFACEs

### PR DESCRIPTION
**Pull request by mcgratta**

### CODE REVIEW

**Comment by rmcdermo** [comment]
Was anything different about how you merged this?  I did not get an email

**Comment by mcgratta** [comment]
Nope, my usual routine. Any trouble with the commit?

**Comment by marcosvanella** [comment]
Randy, interesting. I got the email of this commit.
________________________________
De: Kevin McGrattan <notifications@github.com>
Enviado: jueves, 19 de marzo de 2020 05:46 p. m.
Para: firemodels/fds <fds@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Asunto: Re: [firemodels/fds] FDS Source: Extend WALL functions to CFACEs (#8169)


Nope, my usual routine. Any trouble with the commit?

**Comment by rmcdermo** [comment]
I eventually got it, but only after Kevin's comment.  Must either be a hiccup in GitHub or Gmail.

**Comment by marcosvanella** [comment]
BTW, Kevin, I see you changed several things related to HVAC. If you have some time, feel free to take a crack at the Pressure Zone issue #8122.
________________________________
De: marcos vanella <marcos_vanella@hotmail.com>
Enviado: jueves, 19 de marzo de 2020 05:51 p. m.
Para: firemodels/fds <fds@noreply.github.com>; firemodels/fds <reply@reply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Asunto: Re: [firemodels/fds] FDS Source: Extend WALL functions to CFACEs (#8169)

Randy, interesting. I got the email of this commit.
________________________________
De: Kevin McGrattan <notifications@github.com>
Enviado: jueves, 19 de marzo de 2020 05:46 p. m.
Para: firemodels/fds <fds@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Asunto: Re: [firemodels/fds] FDS Source: Extend WALL functions to CFACEs (#8169)


Nope, my usual routine. Any trouble with the commit?

**Comment by mcgratta** [comment]
I'll take a look at it. I've given you another water droplet case.

**Pull request merged**
