### PR TITLE
Scripts: add -u option for shortcut to _dv version of FDS

### PR DESCRIPTION
**Pull request by rmcdermo**

### CODE REVIEW

**Comment by rmcdermo** [comment]
Glenn,
Please check my changes and merge if they are ok.  Thanks.

**Comment by rmcdermo** [comment]
Glenn,
I did something wrong.  I get this:

[rmcdermo@burn Atmospheric_Effects]$ qfds.sh -p 8 -u wind_example.fds
/home4/rmcdermo/GitHub/FireModels_rmcdermo/fds/Utilities/Scripts/qfds.sh: illegal option -- u

Notice the "illegal" option.

**Comment by gforney** [comment]
I'll check out a branch for this pull request and see if I can figure out what is going wrong. (your changes looked ok to me!)

**Comment by gforney** [comment]
look for this line in qfds.sh
while getopts 'AbB:cd:e:E:f:ij:l:m:Nn:o:p:q:rstw:v' OPTION

change it to
while getopts 'AbB:cd:e:E:f:ij:l:m:Nn:o:p:q:rstuw:v' OPTION

It should work.  

at the risk of TMI!  There is a letter for each option .  a ':' after a letter means it has a parameter (like with -e you also specify the fds name) .  Since -u doesn't have an additional parameter you don't have :

**Comment by rmcdermo** [comment]
Ah, thanks.  Forgot to edit that line.

**Comment by rmcdermo** [comment]
Glenn,
Should be fixed now.  Please have a look.

**Review by gforney — APPROVED** [review]
looks good

**Pull request merged**
