### PR TITLE
Smoothed Algebraic Multigrid and Doxygen in ScaRC

### PR DESCRIPTION
**Pull request by SusanKilian**
This is a new version of ScaRC, which contains various enhancements and new features:

- a Smoothed Algebraic Multigrid variant (SAMG), which works regardless of whether the number of grid cells is divisible by 2 or not and has more powerful interpolation mechanisms than the previous Geometric Multigrid (GMG)
- SAMG can also be used as a preconditioner within the default CG method and thus contribute to a coarse grid coupling
- a basic documentation based on Doxygen
- an internal memory management, which gives information about the memory requirements of ScaRC 
- various other structural optimisations

It seems to me that all my old test cases are still working. Please let me know if you encounter any problems.
At the moment, I cannot make any reliable statements regarding the computational costs of this new variant, but I am in the process of testing the new methodology on various geometries.

Best, Susan

### CODE REVIEW

**Comment by rmcdermo** [comment]
All,
Please do not merge yet.  I will test a branch with firebot.

Susan,
This is a massive commit, with 10k line changes to both read and dump.  When you are touching important files like these, I would prefer more frequent, smaller commits that we can understand and manage.  Thanks

**Comment by mcgratta** [comment]
It appears that the entire read.f90 file is being committed.

**Comment by rmcdermo** [comment]
Likely a line ending problem.  Once I checkout the test branch, I can hopefully fix this kind of stuff.

Susan, does it sound right to you that you've touched every line of read.f90?  If not, we need to close this PR and start over.

**Comment by drjfloyd** [comment]
Not sure what is going on with the PR but if I make a local copy of the
read.f90 in the PR there are only a handful of changes from the current
source.

**Comment by SusanKilian** [comment]
Hi, all,

gah, I have no idea what might have happened here. I even downloaded a completely new clone of the FDS repository before this commit, pushed it into my own repo via 'git push -f origin master', and only then applied my desired changes again. The changes I made in read.f90 only affect lines 8422 to 8476, all other lines I did not touch at all! At the pull request I got the message that these changes can be merged without conflicts. I'm really sorry if this commit is such a big problem, but I don't know what went wrong here. I'm actually trying to keep changes to files other than scrc.f90 as small and manageable as possible. If you find out what might have gone wrong here, please let me know so I can avoid it next time.
Let's close this pull request, I'll try again. 

Susan

**Pull request closed without merging**
