### PR TITLE
Update ht3d_sphere_51.ini file

### PR DESCRIPTION
**Pull request by sbenkorichi**
This correct some of the file configuration in order to give better view of the image.

### CODE REVIEW

**Comment by rmcdermo** [comment]
Please post the new image.

**Comment by sbenkorichi** [comment]
The reason for this is because I think you forgot to change the Truncate data as well.

ht3d_sphere_51_165

**Comment by rmcdermo** [comment]
OK, this is fine.

**Comment by sbenkorichi** [comment]
Thanks !

**Pull request merged**
