### PR TITLE
 FDS Source V&V : Add FORCE_DIRECTION to replace ORIENTATION in distributed force integrals and wall DEVCs.

### PR DESCRIPTION
**Pull request by marcosvanella**

### CODE REVIEW

**Comment by drjfloyd** [comment]
We are we adding a new keyword that simply replicates ORIENTATION which is already familiar to the user?

**Comment by rmcdermo** [comment]
This is different.  We need to get the force direction independent of the IOR and in several parts of the code it is assumed IOR and ORIENTATION are the same.  This is a safe way, for now, of supplying the force direction without breaking other things.  At the moment, this is confined to complex geometry force integrations.  Typical users have never used these outputs.  But, yes, in an ideal world we could have only one parameter.  But today we cannot afford to break everything.  Jesus is here working on a writeup in the user guide, which should be ready soon.

**Comment by marcosvanella** [comment]
This keyword is only used to define forces or distributed forces due to WALL PRESSURE or WALL VISCOUS STRESSES in a direction of preference. Note that it cannot be ORIENTATION in case of pointwise devices because that gets overriden in read.f90 by the IOR DEVC parameter, which just specifies in which direction is the wall.
________________________________
De: Jason Floyd <notifications@github.com>
Enviado: jueves, 24 de octubre de 2019 03:21 p. m.
Para: firemodels/fds <fds@noreply.github.com>
CC: marcosvanella <marcos_vanella@hotmail.com>; State change <state_change@noreply.github.com>
Asunto: Re: [firemodels/fds] FDS Source V&V : Add FORCE_DIRECTION to replace ORIENTATION in distributed force integrals and wall DEVCs. (#7723)


We are we adding a new keyword that simply replicates ORIENTATION which is already familiar to the user?

**Comment by drjfloyd** [comment]
Gotcha. Thanks.

**Comment by marcosvanella** [comment]
BTW this can also be used in external boundaries and OBSTs.
________________________________
De: marcos vanella <marcos_vanella@hotmail.com>
Enviado: jueves, 24 de octubre de 2019 03:28 p. m.
Para: firemodels/fds <fds@noreply.github.com>; firemodels/fds <reply@reply.github.com>
CC: State change <state_change@noreply.github.com>
Asunto: Re: [firemodels/fds] FDS Source V&V : Add FORCE_DIRECTION to replace ORIENTATION in distributed force integrals and wall DEVCs. (#7723)

This keyword is only used to define forces or distributed forces due to WALL PRESSURE or WALL VISCOUS STRESSES in a direction of preference. Note that it cannot be ORIENTATION in case of pointwise devices because that gets overriden in read.f90 by the IOR DEVC parameter, which just specifies in which direction is the wall.
________________________________
De: Jason Floyd <notifications@github.com>
Enviado: jueves, 24 de octubre de 2019 03:21 p. m.
Para: firemodels/fds <fds@noreply.github.com>
CC: marcosvanella <marcos_vanella@hotmail.com>; State change <state_change@noreply.github.com>
Asunto: Re: [firemodels/fds] FDS Source V&V : Add FORCE_DIRECTION to replace ORIENTATION in distributed force integrals and wall DEVCs. (#7723)


We are we adding a new keyword that simply replicates ORIENTATION which is already familiar to the user?

**Pull request merged**
