### PR TITLE
Updating my personal GitHub fork

### PR DESCRIPTION
**Pull request by bmralph**

### CODE REVIEW

**Comment by gforney** [comment]
not sure of the purpose of this pull request .  Don't see any files that were chagned

**Comment by bmralph** [comment]
Sorry, my mistake. I had the compare the wrong way around...

**Comment by rmcdermo** [comment]
Ben,
An easier way (IMO) to stay up-to-date with our central repo is to set up remote tracking.  I discuss how to do this here:
https://github.com/firemodels/fds-smv/wiki/Git-User-Workflow

**Comment by bmralph** [comment]
Thanks Randy, I will have a look.

**Pull request closed without merging**
