### PR TITLE
Update smoke_detector.fds  --  Add SMOKEVIEW_ID

### PR DESCRIPTION
**Pull request by godisreal**
Add SMOKEVIEW_ID='smoke_detector' in PROP
Not sure whether SMOKEVIEW_ID is always required or not.  That's a little confusing.

### CODE REVIEW

**Comment by gforney** [comment]
I'll take a look

**Comment by drjfloyd** [comment]
As a note, SMOKEVIEW_ID isn't required. This parameter only changes how Smokeview displays the device. If you don't give a SMOKEVIEW_ID, then Smokeview just draws the green dot used for other devices.

**Comment by gforney** [comment]
I was going to say the same thing .  SMOKEVIEW_ID just tells smokeview how to draw the object.

**Review by gforney — APPROVED** [review]
OK to merge

**Comment by rmcdermo** [comment]
OK, in future go ahead and merge.  Thanks.

**Pull request merged**
