### PR TITLE
Update FDS+EVAC_Guide

### PR DESCRIPTION
**Pull request by sbenkorichi**
coincide* 
capability*
parameters*
enhanced*
continuously* 
perhaps be*
components*
exactly*
densely*
calculation*

### CODE REVIEW

**Comment by sbenkorichi** [comment]
I dont understand. I've already corrected some of these typos previously. And Kevin has merged them. But, now I see them reappeared again. 
Any explanation?

**Comment by rmcdermo** [comment]
Not sure, Salah.  We'd have to go back through each commit.

**Comment by sbenkorichi** [comment]
I saw Timo few days ago has updated this user guide. Could it be due to that? Or my changed weren't included in his commit at that moment?

**Comment by rmcdermo** [comment]
Right.  Possible that he did not update and merge the latest branch before making his changes.

**Comment by sbenkorichi** [comment]
Ok, thanks,
Anyhow, if I spot other stuff, I would commit pull request for them.
Cheers

**Pull request merged**
