### PR TITLE
shostikk: Add validation files for Tokyo University of Science facade…

### PR DESCRIPTION
**Pull request by shostikk**
Adding files for Tokyo University of Science facade tests to FDS_Validation repository.

### CODE REVIEW

**Comment by rmcdermo** [comment]
Simo,
Nice work using the pull request!

**Comment by shostikk** [comment]
Thanks. 

Now trying to continue from my second repository. The first one was on my PC, now working on linux. Cloning went fine but pushing the upstream pull back to shostikk/fds-smv does not work. Giving 

error: The requested URL returned error: 403 Forbidden while accessing https://github.com/shostikk/fds-smv/info/refs

fatal: HTTP request failed)

**Comment by rmcdermo** [comment]
Did you clone the repo with HTTPS?  If so, have you set up a Personal
Access Token?

**Comment by shostikk** [comment]
I did. But the command line git did not ask it at any point.

**Comment by rmcdermo** [comment]
You use that token as the password.

**Comment by rmcdermo** [comment]
It did not ask for a password?

**Comment by shostikk** [comment]
No

**Comment by shostikk** [comment]
Also, the beginning went a little bit different: I directly received the development branch, not master.

**Comment by rmcdermo** [comment]
Yes, Glenn changed the default branch and we have not yet updated the
wiki.  Sorry.

**Comment by shostikk** [comment]
Ok.

**Comment by shostikk** [comment]
The SSH issue was solved: In my linux system (taito.csc.fi), instead of ssh-agent -s, I had to use 
ssh-agent $SHELL

Then
ssh-add ~/.ssh/id_rsa_taito

Then test
ssh -T git@github.com
And then proceed with git commands

**Comment by rmcdermo** [comment]
Excellent!

On Thursday, July 2, 2015, Simo Hostikka notifications@github.com wrote:

> The SSH issue was solved: In my linux system (taito.csc.fi), instead of
> ssh-agent -s, I had to use
> ssh-agent $SHELL
> 
> Then
> ssh-add ~/.ssh/id_rsa_taito
> 
> Then test
> ssh -T git@github.com <javascript:_e(%7B%7D,'cvml','git@github.com');>
> And then proceed with git commands
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/firemodels/fds-smv/pull/2447#issuecomment-117989788.

## 

Sent from my iPhone

**Pull request merged**
