### PR TITLE
FDS Source: Adjust termination criterion for CG-method

### PR DESCRIPTION
**Pull request by SusanKilian**
This change slightly relaxes the convergence criterion for the CG method.

### CODE REVIEW

**Comment by rmcdermo** [comment]
@SusanKilian Did you test this on the duct flow case?  I thought Marcos and I had looked at this case and compared with GLMAT.  How do you know this is tight enough when you have divergence at mesh boundaries and so on?

**Comment by SusanKilian** [comment]
My recent tests with other cases suggest it's sufficient. But I look at it again.

**Comment by rmcdermo** [comment]
Please see section 9.2 Optional Pressure Solver in the user guide.  Please post the plots for duct_flow and dancing_eddies with these new defaults.  Thanks.

**Comment by SusanKilian** [comment]
I'll do ...

**Pull request merged**
