### PR TITLE
FDS Source: Issue #6714. Add ABSOLUTE_VALUE for DEVC.

### PR DESCRIPTION
**Pull request by mcgratta**

### CODE REVIEW

**Comment by drjfloyd** [comment]
Would this be better as math control function to make it more broadly accessible?

**Comment by mcgratta** [comment]
It could be. But it's easy just to add `ABSOLUTE_VALUE=.TRUE.` on the `DEVC` line rather than extra `CTRL` and `DEVC` lines.

**Comment by drjfloyd** [comment]
Should the ABS be done after any CONVERSION?

**Comment by mcgratta** [comment]
I can't think of a good example.

**Pull request merged**
