### PR TITLE
FDS Source: Fix overflow error in max scaling flux.

### PR DESCRIPTION
**Pull request by drjfloyd**

### CODE REVIEW

**Comment by johodges** [comment]
Thanks for the hotfix. Does the same change need to be made in type.f90 line 796?

**Comment by drjfloyd** [comment]
Since we always set SURF%Min/Max_S_H_F using the values in read, we don't need to set default values in type.f90.  They are always overwritten. Probably best to delete the values from type.f90 that way in the future someone isn't confused about which lines of code actually control the defaults.

**Comment by drjfloyd** [comment]
Another option is keep the default as is in type and in read set the values to -1 and then only replace the SF% value if the user has specified a positive value. Now that I am thinking about this more we should probably also add an error check that any values specified are MAX > MIN >= 0.

**Comment by johodges** [comment]
I agree with your change to have -1 in read, apply the fix for HUGE in type, and add the error check in read. Do you want to make that change on your side in this pull request or do you want me to make it on my side and do a new pull request?

**Comment by mcgratta** [comment]
I  just set the value to 1 billion.

**Pull request closed without merging**
