### PR TITLE
FDS Source : Add HYPRE PG+AMG to UGLMAT.

### PR DESCRIPTION
**Pull request by marcosvanella**
- Added verification case Verification/Pressure_Solver/dancing_eddies_uglmat_hypre.fds. Should run tonight.

### CODE REVIEW

**Comment by rmcdermo** [comment]
@marcosvanella A clean compile of dv mode will give
```
 3927 |    IERR=0; CALL HYPRE_INITIALIZE(IERR)
      |       1
Error: Symbol 'ierr' at (1) has no IMPLICIT type
make: *** [pres.o] Error 1
```

Not exactly sure how you want to handle this, so I leave it to you.

**Comment by marcosvanella** [comment]
Thanks I'll take case of it.

**Comment by marcosvanella** [comment]
care*

**Comment by marcosvanella** [comment]
Should be addressed with the latest PR

**Pull request merged**
