### PR TITLE
FDS Tech Guide: Add diagram of variable positions in a cell

### PR DESCRIPTION
**Pull request by mcgratta**

### CODE REVIEW

**Comment by mcgratta** [comment]
Randy, check out the diagram of a grid cell. See if you want to add more to it.

**Comment by rmcdermo** [comment]
Kevin,
This looks really good!  I have a few suggestions that we can discuss, but this certainly is a great start.

**Comment by bmralph** [comment]
Looks really good and is a helpful place to point students to, who often
have questions about the location of scalers and velocity components.

**Comment by mcgratta** [comment]
I wish I had more time to learn tikz. Then I could do those swirls in 3-D!

**Pull request merged**
