### PR TITLE
FDS Source: Fix minor error in wake reduction

### PR DESCRIPTION
**Pull request by mcgratta**

### CODE REVIEW

**Comment by mcgratta** [comment]
Simo, can you check this, and PR #10203.

**Comment by shostikk** [comment]
I cannot understand why L/D-1/2 was changed to L/D-1.

According to Fig 1 of Ramirez paper, s/d = s_0/d - 1/2. Our L is s_0 (center-to-center distance). s is the distance from the rear-surface of the leading sphere to the center of the second sphere.

**Comment by mcgratta** [comment]
If the two spheres touch, isn't L=D? I was also confused by this, but the denominator of those expressions must go to zero as the spheres get closer and closer.

**Comment by shostikk** [comment]
Why should the denominator vanish at L=D? Yes, at L=D the two spheres touch, and the drag has its smallest value. It is not zero, though. The authors of the paper compare their model against another one, and discuss their decision to use the surface-to-center distance instead of center-to-center.

**Comment by mcgratta** [comment]
OK -- I just assumed that the denominator should go to zero. I'll fix.

**Pull request merged**
