### PR TITLE
FDS Documentation: Update guide for AL2O3 change

### PR DESCRIPTION
**Pull request by drjfloyd**

### CODE REVIEW

**Comment by rmcdermo** [comment]
Jason,
Lots of compile errors in _db with the new irad.  Please fix asap.

**Comment by drjfloyd** [comment]
I don't get any errors.

**Comment by rmcdermo** [comment]
OK, I had a problem with my cons.

But are you not seeing this in velo?

Feb 9 14:08:08 2016 -0500\"" -DBUILDDATE_PP=\""Feb 09, 2016  14:08:25\""
-openmp -openmp-link static -liomp5 ../../FDS_Source/velo.f90

../../FDS_Source/part.f90(2569): error #6460: This is not a field name that
is defined in the encompassing structure.   [MELTING_TEMPERATURE]

```
     AVG_DROP_TMP(:,:,:,LPC%ARRAY_INDEX ) =
```

MAX(SPECIES(LPC%Y_INDEX)%MELTING_TEMPERATURE,AVG_DROP_TMP(:,:,:,LPC%ARRAY_INDEX
))

-------------------------------------------------------------------------^

../../FDS_Source/part.f90(2569): error #6362: The data types of the
argument(s) are invalid.   [MAX]

```
     AVG_DROP_TMP(:,:,:,LPC%ARRAY_INDEX ) =
```

MAX(SPECIES(LPC%Y_INDEX)%MELTING_TEMPERATURE,AVG_DROP_TMP(:,:,:,LPC%ARRAY_INDEX
))

----------------------------------------------------^

compilation aborted for ../../FDS_Source/part.f90 (code 1)

make: **\* [part.o] Error 1

make: **\* Waiting for unfinished jobs....

**Comment by mcgratta** [comment]
I get that error.

**Comment by gforney** [comment]
this is what I am seeing - I assume randy is seeing the same

Intel(R) Visual Fortran Intel(R) 64 Compiler for applications running on
Intel(R) 64, Version 16.0.1.146 Build 20151021
Copyright (C) 1985-2015 Intel Corporation.  All rights reserved.

Intel(R) Visual Fortran Intel(R) 64 Compiler for applications running on
Intel(R) 64, Version 16.0.1.146 Build 20151021
Copyright (C) 1985-2015 Intel Corporation.  All rights reserved.

Intel(R) Visual Fortran Intel(R) 64 Compiler for applications running on
Intel(R) 64, Version 16.0.1.146 Build 20151021
Copyright (C) 1985-2015 Intel Corporation.  All rights reserved.

../../FDS_Source/part.f90(2569): error #6460: This is not a field name that
is defined in the encompassing structure.   [MELTING_TEMPERATURE]
         AVG_DROP_TMP(:,:,:,LPC%ARRAY_INDEX ) =
MAX(SPECIES(LPC%Y_INDEX)%MELTING_TEMPERATURE,AVG_DROP_TMP(:,:,:,LPC%ARRAY_INDEX
))
-------------------------------------------------------------------------^
../../FDS_Source/part.f90(2569): error #6362: The data types of the
argument(s) are invalid.   [MAX]
         AVG_DROP_TMP(:,:,:,LPC%ARRAY_INDEX ) =
MAX(SPECIES(LPC%Y_INDEX)%MELTING_TEMPERATURE,AVG_DROP_TMP(:,:,:,LPC%ARRAY_INDEX
))
----------------------------------------------------^
compilation aborted for ../../FDS_Source/part.f90 (code 1)
make: **\* [part.obj] Error 1
make: **\* Waiting for unfinished jobs....

On Tue, Feb 9, 2016 at 2:09 PM, Randy McDermott notifications@github.com
wrote:

> OK, I had a problem with my cons.
> 
> But are you not seeing this in velo?
> 
> Feb 9 14:08:08 2016 -0500\"" -DBUILDDATE_PP=\""Feb 09, 2016 14:08:25\""
> -openmp -openmp-link static -liomp5 ../../FDS_Source/velo.f90
> 
> ../../FDS_Source/part.f90(2569): error #6460: This is not a field name that
> is defined in the encompassing structure. [MELTING_TEMPERATURE]
> 
> AVG_DROP_TMP(:,:,:,LPC%ARRAY_INDEX ) =
> 
> MAX(SPECIES(LPC%Y_INDEX)%MELTING_TEMPERATURE,AVG_DROP_TMP(:,:,:,LPC%ARRAY_INDEX
> ))
> 
> -------------------------------------------------------------------------^
> 
> ../../FDS_Source/part.f90(2569): error #6362: The data types of the
> argument(s) are invalid. [MAX]
> 
> AVG_DROP_TMP(:,:,:,LPC%ARRAY_INDEX ) =
> 
> MAX(SPECIES(LPC%Y_INDEX)%MELTING_TEMPERATURE,AVG_DROP_TMP(:,:,:,LPC%ARRAY_INDEX
> ))
> 
> ----------------------------------------------------^
> 
> compilation aborted for ../../FDS_Source/part.f90 (code 1)
> 
> make: **\* [part.o] Error 1
> 
> make: **\* Waiting for unfinished jobs....
> 
> On Tue, Feb 9, 2016 at 2:05 PM, Jason Floyd notifications@github.com
> wrote:
> 
> > I don't get any errors.
> > 
> > On Tue, Feb 9, 2016 at 2:02 PM, Randy McDermott <
> > notifications@github.com>
> > wrote:
> > 
> > > Jason,
> > > Lots of compile errors in _db with the new irad. Please fix asap.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/firemodels/fds-smv/pull/3457#issuecomment-182007345
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/firemodels/fds-smv/pull/3457#issuecomment-182008819
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/firemodels/fds-smv/pull/3457#issuecomment-182010908.

## 

Glenn Forney

**Comment by drjfloyd** [comment]
Missed selecting part.f90 when I pushed earlier.  We had both MELTING_TEMPERATURE and TMP_MELT and VAPORIZATION_TEMPERATURE and TMP_V in SPECIES_TYPE.  I got rid of the duplication (the pairs were not being initialized the same).

**Pull request merged**
