### PR TITLE
Fix qfds for SLURM at CSC(Finland)

### PR DESCRIPTION
**Pull request by shostikk**
This now works at taito.csc.fi
- nodes cannot be higher than 1 in the 'serial' queue. Now it is not set at all, and SLURM will decide.
- walltime must be set
- MPIRUN command is srun

Could not test for not breaking PBS.

### CODE REVIEW

**Comment by mcgratta** [comment]
Thanks, Simo. 

Randy, Marcos -- do you see any problems with these changes if running on AWS?

**Comment by shostikk** [comment]
Are you using Slurm as well?

L?hetetty iPhonesta

Kevin McGrattan <notifications@github.com<mailto:notifications@github.com>> kirjoitti 14.11.2017 kello 15.42:


Thanks, Simo.

Randy, Marcos -- do you see any problems with these changes if running on AWS?

-

**Comment by rmcdermo** [comment]
We'll see when we get there.  Every time I log into scorch there is something not working.  So, I am yet to have a successful run.  That doesn't mean that the next time I try it will be ok.  But it generally is not a 5 minute exercise.

**Comment by mcgratta** [comment]
On the NIST clusters, we use OpenPBS/Torque. If you just execute qfds.sh like this:
```
qfds.sh -p 12 -v simo.fds
```
you can see what the default settings are.

**Pull request merged**
