### PR TITLE
FDS user guide: further clarification of MTR

### PR DESCRIPTION
**Pull request by bmralph**
Further explanation following user confusion.

### CODE REVIEW

**Comment by rmcdermo** [comment]
@bmralph Can we hold off on this change?  I am not sure I agree with it and it is not simple to compile and read everything in context without cluster access (doable but not a snap).  Thanks.

**Comment by bmralph** [comment]
Yup of course.

**Comment by bmralph** [comment]
Hi @rmcdermo; now you're back online would you mind having a look at this PR? Cheers, B

**Comment by rmcdermo** [comment]
@bmralph Thanks for the reminder.  I am doing some other surgery on user guide right now and will combine your proposed changes with other updates.

**Comment by bmralph** [comment]
Roger that!

**Comment by rmcdermo** [comment]
OK, I push up a few changes.  See if you approve.

**Comment by bmralph** [comment]
Addresses what I think was missing yip! Cheers Randy

**Comment by rmcdermo** [comment]
Thanks for the help!

**Pull request closed without merging**
