### PR TITLE
Update McCaffrey_*_kw_11 mult mesh lines

### PR DESCRIPTION
**Pull request by sbenkorichi**
While testing the 11 cases, a warning on the devices is shown : 
WARNING: DEVC tmp is not within any mesh.
WARNING: DEVC vel is not within any mesh.

This PR fixes it.

### CODE REVIEW

**Comment by sbenkorichi** [comment]
@rmcdermo 
Review plz when you're at office.

**Comment by rmcdermo** [comment]
Salah,
Sorry, but I am not changing these input files until after release.  We can live with the DEVC warnings for now.

**Comment by sbenkorichi** [comment]
That's Ok.

**Comment by sbenkorichi** [comment]
Here is one way how one could clean a commit that doesn't go into the HEAD master,
I was tired of each time deleting and reforking new repo.

`~/firemodels/fds $ git log`

This was the las commit before mine done by Kevin 
```
commit a8d7fb1f2a83c6b4bc46d13ca1e1209d223bd031
Merge: d38f50a c3ac10a
Author: Kevin McGrattan <mcgratta@users.noreply.github.com>
Date:   Fri Sep 29 17:34:47 2017 -0400

    Merge pull request #5536 from mcgratta/master
    
    FDS Validation: Edits to NIST/NRC Cabinet input files
```
Then
```
~/firemodels/fds $ git reset --hard a8d7fb1f2a83c6b4bc46d13ca1e1209d223bd031
HEAD is now at a8d7fb1 Merge pull request #5536 from mcgratta/mast
~/firemodels/fds $ git push origin master --force
```

Now, my repo is even with firemodels:master.

**Comment by rmcdermo** [comment]
Another way is to work with topic branches, which can be purged if they are not accepted.

**Comment by sbenkorichi** [comment]
Yes, I saw some recommending it, I will try that way next time.

**Pull request closed without merging**
