### PR TITLE
FDS Source: Issue #13564. Clarify meaning of Z_REF

### PR DESCRIPTION
**Pull request by mcgratta**

### CODE REVIEW

**Comment by drjfloyd** [comment]
The new guide text says that if Z_REF isn't given it is taken as 2 m above the ground level but the souce code just has Z_REF=2 not GROUND_LEVEL+2.

**Comment by drjfloyd** [comment]
For Z_REF is there a reason for 2 m? If you are grabbing data from a local weather station those are often taking speed at ~10 m.

**Comment by mcgratta** [comment]
`Z_REF` is a relative value, at least now it is. Its default is 2 m above ground level, which is 0 by default. Not sure why 2 m was chosen.

**Comment by drjfloyd** [comment]
According to the guide text if I were to set GROUND_LEVEL=10 then Z_REF would be 12 (10+2).  In the source, Z_REF would just be 2.  I think that Guide or source should be changed to reflect the other.

10 might be better. The World Meteorlgoical Organization standard for wind measurment is 10 m.

5.9.2	anemometers	over	land 
The standard exposure of wind instruments over level, open terrain is 10 m above the ground.

**Pull request merged**
