### PR TITLE
FDS Source : Add unstructured projection residuals computation, link …

### PR DESCRIPTION
**Pull request by marcosvanella**
…pressure.

### CODE REVIEW

**Comment by marcosvanella** [comment]
@TristanHehnen your PR checks in action. My version of GCC hadn't picked up the unused variable (fixed in the 2nd commit). Good work!

**Comment by rmcdermo** [comment]
Might want to thank @marcfehling too ;)

**Comment by marcosvanella** [comment]
Oh yes, nice work @marcfehling !

**Comment by TristanHehnen** [comment]
Hm, I'm a bit confused here, which PR checks exactly? Maybe it is someone else that should receive the credit for it?

**Comment by marcosvanella** [comment]
Hi Tristan, sorry I meant Marc in the original message. The FDS compilation with intel and gnu compilers is checked automatically every time a PR is opened now.

**Comment by TristanHehnen** [comment]
Alright, no worries... :D

Good job, Marc!

**Comment by marcfehling** [comment]
Glad to hear that you're happy with this feature :)

**Pull request merged**
