### PR TITLE
FDS Verification: fixed naming for HVAC figure plotting

### PR DESCRIPTION
**Pull request by bmralph**
_Fixed referencing of ideal data in FDS_verification_dataplot_input.csv.
_Renamed Ideal data in other csv files for HVAC figures (from exact to ideal for consistency). I've generated all relevant dataplots using FDS_verification_script.m and they're running fine now.

NOTES ON EOL @rmcdermo :
_When I `add`'d dataplot input csv I was given the warning:

> warning: CRLF will be replaced by LF in Utilities/Matlab/FDS_verification_dataplot_inputs.csv.
> The file will have its original line endings in your working directory.

_When I `diff`'d the input csv file only lines 122-130 were shown as changes. However upon pull request 338 additions, 338 deletions are being shown.

### CODE REVIEW

**Comment by rmcdermo** [comment]
This is what I expect to see for awhile as the new line endings migrate up to the repo.

**Comment by rmcdermo** [comment]
I'm searching for a safe way to fix all the files at once.  But I haven't figured this out yet.

**Comment by rmcdermo** [comment]
Ben,
This is my bad for not catching this, but the diff what not only because of line endings.  The d's in the first column had been changed to s.  Kevin has fixed it.

**Comment by bmralph** [comment]
My bad. I think I changed the first column but didn't save prior to
committing. _slaps forehead_

**Pull request merged**
