### PR TITLE
Collapsing divg.f90 and annotation cleanup

### PR DESCRIPTION
**Pull request by ksuarez1423**

### CODE REVIEW

**Comment by rmcdermo** [comment]
@mcgratta Let's run this through firebot before merging.  Thanks.

**Comment by mcgratta** [comment]
First run firebot using the instructions [here](https://github.com/firemodels/bot/tree/master/Firebot)

**Comment by klockheart** [comment]
Definitely. I did not previously know how to use firebot, but will definitely use it now.

**Comment by mcgratta** [comment]
I am closing this PR. Do full updates of everything and than issue a new PR.

**Pull request closed without merging**
