### PR TITLE
FDS Source: Overhaul of convective heat transfer models

### PR DESCRIPTION
**Pull request by mcgratta**

### CODE REVIEW

**Comment by rmcdermo** [comment]
Could the `Validation/Vegetation/` directory be `Frankman_Vegetation`?  I worry about having another "Pool_Fires" directory that should really be "VTT_Pool_Fires"

**Comment by drjfloyd** [comment]
Why go back to hard coding the various heat transfer coefficients? It doesn't substantially impact code complexity.

**Comment by ericvmueller** [comment]
I agree with Jason - the custom coefficients were very helpful for the work we did on convection in vegetation beds, and I guess will be helpful for any continued convection studies in the small tunnel at NIST.

**Comment by mcgratta** [comment]
I can add back the coefficients.

**Pull request merged**
